### ISSUE TITLE
JetPack stuff is broken

### ISSUE THREAD

**Issue by nmaier** [scriptish/scriptish#102]
See https://github.com/scriptish/scriptish/issues/72#issuecomment-18779715
Seems the SDK requires a properly setup environment (the stuff from sdk/system).
IMO the SDK stuff should be reverted for now and another point release made.

**Comment by nmaier** [comment]
PS: This is the error message

```
Error: console is not defined
Source file: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js
Line: 34
```

**Comment by erikvold** [comment]
I forgot to setup the loader's globals, almost have a patch.  Busy moving today and doing a maker faire tomorrow but I'll fit it in someplace and do a 1.10

**Comment by nmaier** [comment]
Invalid per 9fa2a3dfa5108a1756a2326a62025020ac384cb3
