### ISSUE TITLE
Icon not working correctly on scriptish 0.1.10

### ISSUE THREAD

**Issue by ghost** [scriptish/scriptish#103]
The icon does not work like it should, 
center click does nothing; it should open the scripts manager, 
right click does nothing; it should open the menu, 
left click opens the menu; it should deactivate scriptish

it was ok on scriptish 0.1.8

**Comment by LouCypher** [comment]
It's by design. See issue #85.

**Comment by ghost** [comment]
Seriously?, Oh, well, looks like i'm not reinstalling again Scriptish, im a very long time user of scriptish and recently i had to return to Greasemonkey because the lack of support on Firefox 24, i got very annoyed on greasemonkey lack of central click, and i got very exited because scriptish got updated again but now i don't see advantage on scriptish, since the scriptish better interface was the reason to use in the first place, i got accustomed to it, seriously, as scriptwriter it was very useful

**Comment by erikvold** [comment]
Is it just middle click you want back?

**Comment by ghost** [comment]
yep

**Comment by LouCypher** [comment]
> center click does nothing; it should open the scripts manager, 

Greasemonkey actually had that feature.
I remember because it was [my](https://groups.google.com/d/msg/greasemonkey-dev/FZOA8cX3AH4/6_xhTMRpLKsJ) [patch](https://www.mozdev.org/bugs/show_bug.cgi?id=15827), copying Stylish.
I don't know when and why was it removed.

Sorry for OT.

**Comment by erikvold** [comment]
Well I think we can add middle click back, sorry I wasn't more vocal about the change.  I will write a blog post about it soon.  We want to conform with typical button usage.

**Comment by erikvold** [comment]
I'm thinking that a Scriptish+ power user add-on may be best here, re-implementing the old behavior.  This way the Scriptish button behaves the same way every other button does by default so as not to surprise new users, and those that want different behavior can have it too.

**Comment by nmaier** [comment]
I restored the middle-click open manager stuff.
As for the rest, I agree with @erikvold that this should be either a hidden pref or a seperate power user add-on (or combination of both, like Customizations for Adblock Plus)

**Comment by ghost** [comment]
Thanks :)

**Comment by erikvold** [comment]
This looks done, let me know if I am wrong.
