### ISSUE TITLE
Toolbar icon is glitched on v0.1.10

### ISSUE THREAD

**Issue by SlimShayD** [scriptish/scriptish#107]
I updated today from v0.1.8 to v0.1.10, and the toolbar icon now consists of a palet of default icons. It's wide and unusable.
I'm on Ubuntu 13.04 and Firefox 21. I've tried disabling the extension, restart browser, re-enable it again, didn't change a thing.

**Comment by erikvold** [comment]
confirmed.

**Comment by Rocka84** [comment]
confirmed under Xubuntu 12.04.2
Albeit in disabled state the icon is ok.

**Comment by mvario** [comment]
Same problem, Firefox Aurora 23.0a2 (2013-06-13), Xubuntu 13.04

**Comment by nmaier** [comment]
Anybody got a screenshot?

**Comment by mvario** [comment]
![selection_001](https://f.cloud.github.com/assets/4701666/657277/7abec6a8-d548-11e2-8c88-d90ba39511f7.png)

**Comment by nmaier** [comment]
k, thanks.
I guess I know the cause already (forgot to make one `#scriptish-button` into a `.scriptish-button`). Should only affects"large" icons and therefore unix (incl. linux, but not mac) as it is the only theme actually using large icons.

**Comment by mvario** [comment]
The icon in the "customize toolbar" window actually looks normal. It just gets wonky if dragged back to the toolbar.  Glad to hear you have identified the issue so quickly.  Thank you!

**Comment by nmaier** [comment]
Alright. 5735b88d6b039ea7b16de1dbb6e998618c2a98c5 seem to be working across platforms and address this problem.

Would be great if some of you could test the scriptish nightly once the next one gets created to verify this as fixed.
https://github.com/scriptish/scriptish-nightlies/downloads

**Comment by mvario** [comment]
Certainly.  Rough guess when it will be available for testing?

**Comment by nmaier** [comment]
Why wait indeed. I just generated a new nightly manually.

**Comment by mvario** [comment]
Cool. Installing now.

**Comment by mvario** [comment]
Okay, looks good. Icon back to normal. Thanks very much!
