### ISSUE TITLE
Having the Scriptish toolbar icon in the toolbar causes the icon itself and the space under the awesomebar to appear deformed for a second at Firefox launch.

### ISSUE THREAD

**Issue by darkred** [scriptish/scriptish#108]
Having the Scriptish toolbar icon in the toolbar (instead of the statusbar, where it's initial position at Scriptish install)
causes itself and the space under the awesomebar to appear deformed for a second at Firefox launch.

To reproduce:
- create a new Firefox 21 profile (in Windows 8)
- install Scriptish 0.1.10 & restart Firefox
- press ctrl+/ to open statusbar, rightclick on it and press Customize, and then drag'n'drop the Scriptish toolbar icon to the toolbar.
- restart Firefox.

You will notice that the Scriptish toolbar icon and the space under the awesomebar appear deformed for a second at Firefox launch.

Here is screenshot of the problem at Firefox launch:
![pic1](https://f.cloud.github.com/assets/723651/650074/fb534546-d453-11e2-8df4-60daad914111.png)
Here is a screenshot a second later:
![pic2](https://f.cloud.github.com/assets/723651/650075/00cdfdc2-d454-11e2-945f-f8cfe6ec9367.png)

Having another addon installed, such as AdBlock Plus,
which itself makes Firefox launch slower,
makes the issue even more visible.

On the other hand, having Greasemonkey 1.9 instead of Scriptish
doesn't cause this.

**Comment by nmaier** [comment]
Hard to reproduce, because I lack a "slow" system that actually shows this and even scaling down the CPU contingent for a VM doesn't really seem to help (seems I/O bound), but it is noticeable a bit.

**Comment by nmaier** [comment]
Can you please verify the glitching is gone or at least significantly better in the next nightly that will be generated in a couple of hours from now?
https://github.com/scriptish/scriptish-nightlies/downloads

**Comment by nmaier** [comment]
Why wait indeed. I just generated a new nightly manually.

**Comment by darkred** [comment]
Just tried 0.1.11 and it's indeed fixed.
Thank you.
