### ISSUE TITLE
@optimize

### ISSUE THREAD

**Issue by KOLANICH** [scriptish/scriptish#111]
Make new metadata block property @optimize to make optimization using Closure Compiler via its [REST API](https://developers.google.com/closure/compiler/docs/api-tutorial1).
@optmize number or string representing [optimization level](https://developers.google.com/closure/compiler/docs/compilation_levels)
-1 or DISABLED disables optimization
-2 or ALREADY_OPTIMIZED to mark already optimized script
0 or WHITESPACE means lianerization of JS, can be processed on client using simple regex;
1 or SIMPLE means simple optimizations;
2 or ADVANCED means advanced optimizations.
if | PRETTY is added pretty-print is enabled

Optimization is made on installation. If the script is changed in folder no optimization is applied.
Default level is configured via preferences. Default level is SIMPLE.
If Closure Compiler is unavailable or warnings or errors were produced it uses unoptimized version.

**Comment by erikvold** [comment]
Well I'm -1 for using a remote api when this can be done locally.  Otherwise I'm +1 for  this, I think we can use the [SourceMap.jsm](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/SourceMap.jsm) to help with debugging if it's needed.

**Comment by KOLANICH** [comment]
It can be done fully locally, but then a user will have to have Java on his computer and you'll have to add code maintaining Closure Compiler version. Scripts are usually distributed through Net so a user have to be online to download a script, so I don't think that using Closure Compiler API is bad. The solution can be to give the user choice which CC to use : online service or local version, or not to use at all. In the second case user must provide the path to its jar file.

**Comment by optimize** [comment]
Please stop sending me emails that are not for me
Thanks

Sent from my iPhone
Alastair Black
Ablack@optimize.ltd.ukmailto:Ablack@optimize.ltd.uk
+44 7779 239076 mobile
+44 20 3287 6103 Skype

On 5 Jul 2013, at 14:08, "KOLANICH" <notifications@github.com<mailto:notifications@github.com>> wrote:

It can be done fully locally, but then a user will have to have Java on his computer and you'll have to add code maintaining Closure Compiler version. Scripts are usually distributed through Net so a user have to be online to download a script, so I don't think that using Closure Compiler API is bad. The solution can be to give the user choice which CC to use : online service or local version, or not to use at all. In the second case user must provide the path to its jar file.

**Comment by erikvold** [comment]
@optimize your name friend ;)

**Comment by LouCypher** [comment]
Blame @GitHub for copying @twitter.

Anyway, let's use `@optimize` from now on.

**Comment by erikvold** [comment]
I think we ought to measure how much this will actually help before making a change like this, I have doubts that it worth doing.

We should start collecting telemetry on things like average number of scripts used, and the avg size of these scripts.  Greasemonkey has started collecting some telemetry, not sure if this type of data is beoing collected though.
