### ISSUE TITLE
Scriptish Addons extend Scriptish API using Jetpack addons & modules

### ISSUE THREAD

**Issue by SlimShayD** [scriptish/scriptish#112]
There have been a couple of occasions where I want to give Scriptish/userscripts more power. Since userscripts are supported by many different browsers and technologies, 
userscript devs have resorted to using hacks in their userscripts, to ensure or fake compatibility. There's no way around that, so we might as well embrace the notion that userscript devs want more flexibility and access to new methods.

How about a new thing? Let's call it a Scriptish Addon. In case another browser implements a new userscript API method, we could write code for the custom Scriptish Addon that does it similar. And the existing userscripts will have access to the same method, after updating the Scriptish Addon ofcourse.

Let's say the userscript let's the user reorder elements of a website, you want to save that data. We can already do that. How about an (basically) external dialog where you can assign priority to the static/known elements of the website. After confirming, the data from the dialog, the module would send back the data to the userscript.

Another usecase would be an API method for a general config/preferences dialog. Allowing userscripts to send data to a dialog to load different kinds of settings to be changed. Examples: A userselect box to change a theme, a checkbox to load an externally hosted theme, a text input for a username to use, a "color select" icon to provide a color swatch or something.

And more advanced: you could allow users to start a download for an item, by clicking an element on a webpage. Or load and parse a RSS feed to show some data in a dialog. Or an import/export method for users to load/store their settings data.

A Scriptish Addon would allow users to interact better with their userscripts, than just expect things to happen predictably to a website.

**Comment by erikvold** [comment]
Good idea @SlimShayD I have been chewing on an idea like this, basically exposing `require` to a userscript, and developing powers thru that interface, CommonJSifying user scripts.  But I think we can make jetpack development much easier too, and that is what I'm focused on these days, also I think the right place for a new idea would be in a new add-on, this way users can opt in to the add-on types they want without getting a package, and I want Scriptish to support traditional user scripts amap for the rest of time.

**Comment by erikvold** [comment]
Note: [once Scriptish has been converted to be a jetpack](https://github.com/erikvold/scriptish) it'll be much easier to fork and create this `common user js` type of add-on
