### ISSUE TITLE
Cannot install scriptish to any browser except firefox

### ISSUE THREAD

**Issue by NessaishereDuck** [scriptish/scriptish#115]
I seem to have no options for installing scriptish to seamonkey or avant or other browsers anymore. This was possible but has been a while since I have had a need for scripts. Now? I cannot install other than to fox.

**Comment by LouCypher** [comment]
WFM on SeaMonkey 2.19.

**Comment by NessaishereDuck** [comment]
OK but how did you manage to install it?

The only links I find will only install on firefox and not on seamonkey.
----- Original Message -----

**Comment by LouCypher** [comment]
> OK but how did you manage to install it?

Go to [Sciptish page on AMO](https://addons.mozilla.org/seamonkey/addon/scriptish/) and click _Add to SeaMonkey_ as usual.

**Comment by NessaishereDuck** [comment]
The only option I get is add to firefox nothing else. Why can't I just download the dang file like always used to. Then I can add it to any browser I want?

**Comment by nmaier** [comment]
Yeah, works for me SM 2.19 from https://addons.mozilla.org/addon/scriptish
Also, older versions are still available from https://addons.mozilla.org/de/firefox/addon/scriptish/versions/
