### ISSUE TITLE
Sry I would just like a response as to why it cannot be downloaded

### ISSUE THREAD

**Issue by NessaishereDuck** [scriptish/scriptish#117]
It seems that both my issues have been closed. I apologize if I offended, but I did not see where I said I was accused of anything and I thought I had been calm. Apologies if I did not appear so.

 I just would like to be able to download the actual file without needing to do the source and then do a make. I would like the option of just having it install like the button does now or, downloading the script in such a manner as was always the norm and then when I opened that file from the addons for any browser it would install. 

Did you ever use GM or Sciptish before it did the "install it for you" thing? In the past, whenever you wanted or needed a script, you could click on a button and download the file. I don't think that is difficult to do and it would allow non-supported browsers that can use Scriptish just fine, actually use it. Like Avant for one. Another big plus is if for any reason you need to uninstall the addon, you do not need to redownload it. Just open the file in your addons area and click install. Does that make any sense to you? Let me find you a GM script that still works the old way...

http://userscripts.org/scripts/show/92257

This does not auto install, it either downloads a file or gives you the script needed to install the thing. From there I can save the code then open it in my add-ons section of my browser and it asks me if I want to install it. I click yes, and it then installs in that browser. This script is for a site called conquerclub and it manages your on site chat for you very nice to have. Does this make sense now?

**Comment by nmaier** [comment]
Please don't file new tickets for the same thing and stick to commenting on the one(s) you already created.
