### ISSUE TITLE
Interesting bug

### ISSUE THREAD

**Issue by derbenx** [scriptish/scriptish#120]
Ok, not sure if it's been mentioned or if it's even a scriptish issue but I figured I'd pass along the info:

if you create a textbox:

<code>var texb = document.createElement('textarea');
 texb.id="debug";
 texb.style.top='20px';
 texb.style.right='0px';
 texb.style.position="fixed";
 texb.innerHTML="text here";
 texb.rows=20;
 texb.cols=80;
 document.getElementsByTagName('body')[0].appendChild(texb);</code>

and then access it by:
<code>document.getElementById('debug').innerHTML='ok';</code>

It works, but if you manually type in the box at any point the above code does nothing. However progmatically it updates and you can read what you put there, it just doesn't update the textarea on the screen.

*before anyone asks, yes, <code>document.getElementById('debug').value</code> works as expected... and is what one should be using. But so does innerHTML, unless you type in the box.

**Comment by erikvold** [comment]
You should use the `value` property.
