### ISSUE TITLE
Support Greasemonkey's GM_info

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#126]
Scriptish developed `GM_getMetadata` first then Greasemonkey introduce `GM_info` which will be redundant for us, but we might as well provide that too now..

**Comment by erikvold** [comment]
http://wiki.greasespot.net/GM_info

**Comment by erikvold** [comment]
Ugh after looking at GM_info closer it is an ugly beast.. I'm not sure it'll make 0.1.12

**Comment by alexolog** [comment]
Useful scripts can no longer work because GM_info is not supported.
Please implement.

**Comment by vBm** [comment]
+1 for this.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
