### ISSUE TITLE
Doesn't run scripts when loading next google page

### ISSUE THREAD

**Issue by adam-frisby** [scriptish/scriptish#127]
I've made a simple script that should load on every page. It just logs the pages url.

``` javascript
// ==UserScript==
// @name         Test
// -------------------------------------------------------------------------------------
// @match        *://*/*
// @run-at       document-end
// ==/UserScript==

console.log(location.href)
```

Instructions:
Open web console
Visit a Google search page [https://www.google.com/#q=Test&fp=1]
Notice the url is logged to the console
Click next page button
Notice the url is not logged to the console

**Comment by supahgreg** [comment]
https://developer.mozilla.org/docs/Web/Reference/Events/hashchange
