### ISSUE TITLE
Support e10s again, the new one

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#128]
https://wiki.mozilla.org/Electrolysis

**Comment by nmaier** [comment]
Really need to do this now since Nightly got it enabled now. Targeted for 36 or 37 officially but I personally think this is a rather optimistic estimation....

GM issue: https://github.com/greasemonkey/greasemonkey/issues/2004

**Comment by erikvold** [comment]
I'm going to try to hack on this over the weekend

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
