### ISSUE TITLE
Additional handling of `@grant`

### ISSUE THREAD

**Issue by supahgreg** [scriptish/scriptish#132]
Wanted to propose supporting multiple `GM_` values per `@grant`, for example:

``` javascript
// @grant  GM_getValue GM_setValue GM_xpath
```

versus

``` javascript
// @grant  GM_getValue
// @grant  GM_setValue
// @grant  GM_xpath
```

One per line seems a bit verbose, and supporting both forms would be trivial.  Then again, the second form is pretty common...

**Comment by erikvold** [comment]
+1
