### ISSUE TITLE
Make @grant optional or remove it all together

### ISSUE THREAD

**Issue by ghost** [scriptish/scriptish#133]
- The number of existing scripts combined with the much larger user base of Greasemonkey puts Scriptish in an unfavorable position to require grant. Scripts not working will be perceived as shortcoming of Scriptish.
- Most GM_\* functions are harmless. Having to whitelist something like GM_log and GM_addStyle seems silly to me.
- Listing permissions like suggested in issue #122 is probably more overwhelming than helpful for most end users.
- It creates a false sense of security. A script doesn't need GM_\* functions in order to mess with unsafeWindow or to send cookies via query string of embedded content.

**Comment by erikvold** [comment]
Alright let's make it optional, I was wrong.

**Comment by erikvold** [comment]
Greasemonkey probably has some scanning code we can use, let's just do what GM does.

**Comment by supahgreg** [comment]
https://github.com/greasemonkey/greasemonkey/blob/master/modules/script.js#L711
https://github.com/greasemonkey/greasemonkey/blob/master/modules/util/sniffGrants.js

**Comment by erikvold** [comment]
> https://github.com/greasemonkey/greasemonkey/blob/master/modules/util/sniffGrants.js

ok that is inefficient, GM is looping thru the source for every grant type..
