### ISSUE TITLE
Need to invent a header that will restrict GM_xhr requests

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#137]
At the moment every userscript that uses GM_xhr can ping any domain, we should have some header that will allow devs to request which domains they intend to actually use, this way that is clear to users and accidental requests in poorly written scripts would be prevented.

**Comment by ghost** [comment]
You mean like the already existing `@domain`?

https://github.com/scriptish/scriptish/blob/master/extension/modules/api/GM_xmlhttpRequester.js#L107

**Comment by erikvold** [comment]
haha totally forgot about that :)
