### ISSUE TITLE
Scriptish nightly builds stopped being generated

### ISSUE THREAD

**Issue by ghost** [scriptish/scriptish#138]
https://github.com/scriptish/scriptish-nightlies/downloads

**Comment by nmaier** [comment]
Yep, it appears the old downloads API is finally really dead.
Back to the drawing board, then...

**Comment by LouCypher** [comment]
Should use [dev channel](https://addons.mozilla.org/addon/scriptish/#beta-channel) on AMO.

**Comment by nmaier** [comment]
The dev channel on AMO sucks.
Created a new https://github.com/nmaier/gh-nightly to produce XPIs and distribute via the github release API.

New nightlies are at https://github.com/scriptish/scriptish-nightlies/releases
