### ISSUE TITLE
Scratchpad integration is broken

### ISSUE THREAD

**Issue by supahgreg** [scriptish/scriptish#142]
As of `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:25.0) Gecko/20130720 Firefox/25.0`, at least...

**Comment by erikvold** [comment]
Seems to be working for me, what wasn't working for you @supahgreg ?

**Comment by nmaier** [comment]
wfm
Build identifier: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:25.0) Gecko/20130720 Firefox/25.0

**Comment by supahgreg** [comment]
@erikvold: The "Save As User Script" item (Scratchpad -> File) seems to be missing.

Looks like `scratchpad.xul` was moved, but I'm not sure why it wouldn't affect either of you.  The following `chrome.manifest` change fixes the issue for me:

``` diff
-overlay    chrome://browser/content/scratchpad.xul chrome://scriptish/content/scratchpad.xul
+overlay    chrome://browser/content/devtools/scratchpad.xul chrome://scriptish/content/scratchpad.xul
```

**Comment by nmaier** [comment]
No, you're right. I never used that menu item and didn't notice it went missing.
You'll want to leave in the old overlay def for now.

**Comment by supahgreg** [comment]
Looks like the change made it into FF 23 (our current minVersion).

**Sources:**
https://bugzilla.mozilla.org/show_bug.cgi?id=679364
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/23#Firefox_Developer_Tools

**Comment by erikvold** [comment]
We'll need to keep the old overlay def in place too, as @nmaier pointed out.

**Comment by erikvold** [comment]
Oh my bad, the move was made in Fx23 but the style did not change.

**Comment by erikvold** [comment]
Thanks @supahgreg !
