### ISSUE TITLE
GM_download

### ISSUE THREAD

**Issue by ghost** [scriptish/scriptish#144]
There's currently no reliable way to trigger downloads.

AFAIK we have
- `location.href = myUrl` - Problem: Supported media types like images open inline. Workround: Read file with GM_xhr and make octet-stream data URI. Yuck. Inefficient and no way to specific file name.
- `a.href = myUrl; a.download = myFilename; a.click();` - Problem: href must be same origin or attribute is ignored.

I suggest a new GM_download with following features:
- everything GM_xmlhttpRequest has (authentication, custom headers, ...)
- `url` (string) - should also accept data URIs and blob objects
- `filename` (string) - If file extension is missing, try to append one based on MIME type.
- `prompt` (boolean) - If true, open Firefox's "You have chosen to open" dialog, otherwise use download directory. If "Always ask me where to save files" is checked, use desktop.

Security considerations:
- Scripts should not be able to choose the directory, just the actual file name.
- Files should never be overwritten unless `prompt` is true. If `prompt` is false and file exists, append "(1)" , "(2)" etc.

**Comment by KOLANICH** [comment]
[There is](https://developer.mozilla.org/en-US/docs/Web/API/URL.createObjectURL).

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
