### ISSUE TITLE
Right-clicking a script to edit shows toolbar context menu, keeps `menupopup` open

### ISSUE THREAD

**Issue by supahgreg** [scriptish/scriptish#149]
Most noticeably when using Scratchpad as the default editor, right-clicking a script to trigger an edit causes:
1. The toolbar context menu to appear briefly (until the Scratchpad window opens).
2. The Scriptish `menupopup` to stay open

`Mozilla/5.0 (Windows NT 6.1; rv:25.0) Gecko/20130721 Firefox/25.0`

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
