### ISSUE TITLE
Add responseType of document to GM_xmlhttpRequest 

### ISSUE THREAD

**Issue by supahgreg** [scriptish/scriptish#15]
In Firefox 11 Mozilla added the responseType of `document` so that you could parse the response as document. Could you add this to the GM_xmlhttpRequest's parameters.

https://developer.mozilla.org/en/XMLHttpRequest#responseType
https://developer.mozilla.org/en/HTML_in_XMLHttpRequest

Source:  https://scriptish.lighthouseapp.com/projects/83146/tickets/615-add-responsetype-of-document-to-gm_xmlhttprequest

**Comment by supahgreg** [comment]
Or maybe not, if the `responseXML` stuff still applies.  Never really looked into that.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
