### ISSUE TITLE
Right clicking a user script in the menu-button should take you to the addon detail page for the user script

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#151]
The addon detail page for user scripts is the one place where you can do everything to a user script, enable/disable, remove, edit, and w/e else we come up with.  At the moment if I want to remove a userscript I have to go to the manage user scripts page, hunt for the script, then finally I can remove it or change update settings or w/e it is I wanted to do, that is waaaay too slow.

We can preserve the currently functionality with an opt-in user pref.

**Comment by vanowm** [comment]
I think a simple menu that would provide enable/disable, edit, details page (where it can be uninstalled or go to home page) would be better.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
