### ISSUE TITLE
scriptish_config.json is too verbose

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#157]
There is no need to save default values like empty arrays in the `scriptish_config.json` file, let's cut this fat.

**Comment by supahgreg** [comment]
Just need to be careful where we expect arrays, etc.  Not necessarily against the idea, but it might get messy for not much gain.

**Comment by erikvold** [comment]
good points @supahgreg also this would kill the possibility of downgrading which I don't like, so let's just close it.
