### ISSUE TITLE
Please provide a working example of Qunit-tested user.js

### ISSUE THREAD

**Issue by ghost** [scriptish/scriptish#158]
According to the documentation, QUnit is the preferred way to test user.js scripts. But there is no article on how to do it.
So, I have tried to write such script myself:

```
// @id             qunit-sample.user.js
// @name           Qunit User.js Scriptish example
// @version        1.0
// @namespace      
// @author         me
// @description    Qunit User.js Scriptish example
// @include        http://dictionary.cambridge.org/*
// @require        http://code.jquery.com/jquery-1.9.0.min.js
// @require        http://code.jquery.com/qunit/qunit-1.12.0.js
// @run-at         document-end
// ==/UserScript==

test( "hello test 1", function() {
ok( 1 == "1", "Passed!" );
});

test( "hello test 2", function() {
ok( 2 == "1", "Passed!" );
});
```

It does not work as expected. It shows success/failure status next to favicon, and nothing more. I can not find a way to see which tests failed

**Comment by supahgreg** [comment]
[Writing Tests](/scriptish/scriptish/wiki/Writing-Tests) and [Running Tests](/scriptish/scriptish/wiki/Running-Tests) refers to testing Scriptish functionality, not userscripts.  See the tests [here](https://github.com/scriptish/scriptish/tree/master/extension/content/tests).
