### ISSUE TITLE
`document.documentElement` and `document.head` are unavailable @ document-start

### ISSUE THREAD

**Issue by nstepien** [scriptish/scriptish#16]
See title.

This works:
- on Firefox with Greasemonkey,
- on Opera,
- on Chrome (except document.head),

but not with scriptish.

**Comment by supahgreg** [comment]
In Scriptish, `@run-at document-start` scripts get injected at `content-document-global-created`, which is before the root element gets inserted.  Greasemonkey (and maybe others) use `document-element-inserted`.

https://developer.mozilla.org/docs/Observer_Notifications

**Comment by supahgreg** [comment]
Whether Scriptish's behavior should be modified is up for debate.  Offhand I can't come up with an example where you'd need to get in before `document-element-inserted`.

**Comment by nstepien** [comment]
I don't think there's much debate to be had when the userscript implementations that matters offer the elements we need at document-start.

**Comment by dindog** [comment]
Does the current implement affect addStlye()? I thought the GM_addStyle is actually creates a style element than appends it to the page...

**Comment by CoolCmd** [comment]
Scriptsh's implementation of document-start useless and must be changed.
At least I shall get access to documentElement or GM_addStyle for preventing flicker.

**Comment by erikvold** [comment]
Alright let's delay injection to conform with the other engines, we can add a new `@run-at` if desired.
