### ISSUE TITLE
After installing a Userscript there should be an undo banner

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#166]
http://alistapart.com/article/neveruseawarning

**Comment by erikvold** [comment]
There should also be an undo action in the doorhanger.

**Comment by nmaier** [comment]
Just saying after seeing what article you linked: We still need confirmation _before_ installing a script. Else a rogue site may trigger install and iframe some third-party site where the new user script would run havoc.

**Comment by erikvold** [comment]
> Just saying after seeing what article you linked: We still need confirmation before installing a script. Else a rogue site may trigger install and iframe some third-party site where the new user script would run havoc.

yep, this is just some added protection against clicking the 'whatever' button mindset.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
