### ISSUE TITLE
GM_safeHTMLParser kills href attributes that don't start with URL scheme

### ISSUE THREAD

**Issue by ghost** [scriptish/scriptish#17]
**Code:**

``` javascript
var examples = [
    '<html><body><a href="http://example.com/foo.bar">Click</a></body></html>',
    '<html><body><a href="/foo.bar">Click</a></body></html>',
    '<html><body><a href="foo.bar">Click</a></body></html>'
];

examples.forEach(function(html) {
    var a = GM_safeHTMLParser(html).querySelector('a');
    GM_log(a.hasAttribute('href'));
});
```

**Output:**

```
true
false
false
```

I'm currently getting by with replacing "href" with "data-href" beforehand. Would be cleaner without it.

**Comment by supahgreg** [comment]
I think the best we'll be able to do is allow you to specify the base URL to resolve any partial URLs.  What you're seeing seems to be a limitation of the underlying code we're using to generate the fragment ([link](https://developer.mozilla.org/docs/XPCOM_Interface_Reference/nsIParserUtils#parseFragment%28%29)).
