### ISSUE TITLE
Add an option to bring back the "disabled on middle click" feature

### ISSUE THREAD

**Issue by Telanor** [scriptish/scriptish#173]
The icon change in v0.1.10 changed the behavior of middle click from disabling scriptish to showing the user scripts window.  As someone who frequently needs to disable scriptish and very rarely ever needs to see a giant list of all my installed scripts, this change is very annoying.

Can we have a setting/preference that brings back the old functionality of disabling on middle click?

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
