### ISSUE TITLE
Cannot use regex patterns for User Includes/Excludes in user script "Preferences" dialog unless "i" flag is used.

### ISSUE THREAD

**Issue by asmblur** [scriptish/scriptish#175]
Attempting to use regular expressions in the User Includes/Excludes for a user script in the script's Preferences dialog _without_ the "i" flag specified causes an error when clicking "OK" and fails to apply the changes.

Cause: Bug in "extension/modules/utils/PatternCollection.js" at line 60 incorrectly assigns 0 to array variable "this._regsSensitives" but should assign 0 to the variable's "length" property:
original:
    this._regs.length = this._regsSensitives = this._regsTLD.length = 0;
fixed:
    this._regs.length = this._regsSensitives.length = this._regsTLD.length = 0;

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
