### ISSUE TITLE
links with "target=_blank" break @run-at document-start function

### ISSUE THREAD

**Issue by dindog** [scriptish/scriptish#18]
https://scriptish.lighthouseapp.com/projects/83146/tickets/602-target_blank-break-some-of-run-at-document-start-function

Here is a testcase:

http://www.cnblogs.com/dindog/articles/2379354.html

A script's src "alert.js" will prompt alert, and this userjs should stop it before it is executed:

``` javascript
// ==UserScript==
// @id             5008e85f-e821-414f-b82a-4fd4c76d5485
// @name           testcase
// @include        http://www.cnblogs.com/*
// @run-at         document-start
// ==/UserScript==
document.addEventListener('beforescriptexecute',
function(e){
    if(e.target.src.indexOf('alert.js') != -1){
        e.preventDefault();
        document.removeEventListener(e.type,arguments.callee,0);
    }
},false);
```

It does, except when the link with attribute "target = _blank", for example,  the RED hyper-link "Click me" in the testcase.

Form submit as target = _blank also affects

**Comment by erikvold** [comment]
This should work in 0.1.12, please reopen this issue if it is not.

**Comment by 0rt** [comment]
I would like to confirm it. Where I can the latest Scriptish now, the nightlies stop update since 2013/07/11
