### ISSUE TITLE
Give userscripts a way to have interactive page(s) dedicated to it

### ISSUE THREAD

**Issue by o-jasper** [scriptish/scriptish#180]
A workaround is to can substitute the current page, but that may be confusing as the browser is otherwise still under the impression that it is visiting the page you substituted.

The interactive pages could for instance help the user set settings, or use the data the user script may have composed. I suppose this is [node-webkit](https://github.com/rogerwang/node-webkit)-like,(though users might want to allow stuff like apparmor to keep stuff separate i.e. on different running instances) so maybe it would be nice to converge some of the API choices.

Of course, it may depend on browsers for implementability. Edit: it is a feature humble, slightly guilty _request_.(other than wording of the title might suggest)

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
