### ISSUE TITLE
Consider providing cross-domain XHR as an alternative to GM_xhr

### ISSUE THREAD

**Issue by nmaier** [scriptish/scriptish#181]
Starting with Firefox24 IIRC, it will be possible to assign multiple origins (principals) to a sandbox. This would enable user scripts to define a set of hosts for cross-domain XHR (without the server having to implement CORS).

The add-on SDK already implemented this: https://addons.mozilla.org/en-US/developers/docs/sdk/Firefox-24/dev-guide/guides/content-scripts/cross-domain.html

It might be a good idea, for compatibility reasons, to allow something similar in Scriptish.

@erikvold Any thoughts about this?

**Comment by erikvold** [comment]
+1  not sure if we should deprecated GM_xhr tho

**Comment by erikvold** [comment]
@domain is used to limit GM_xhr at the moment, it could be used to define the expanded principal too.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
