### ISSUE TITLE
Feature Request: a cookie api to manipulate httponly cookies

### ISSUE THREAD

**Issue by simonzack** [scriptish/scriptish#183]
I propose a cookie api to modify httponly cookies, and if possible, to do this on any website given some special @include setting in the metadata.
This could be useful in a lot of places, google uses httponly cookies a lot for tracking cookies, and it is a good idea to remove them.
I proposed this to the greasemonkey issue tracker too, but it got rejected without any reason.

**Comment by KOLANICH** [comment]
I think it is not such a good idea. Http only cookies were made such for security purposes. We need a special permission for it.
