### ISSUE TITLE
Very simple userscript only seems to start on local files and sporadically

### ISSUE THREAD

**Issue by o-jasper** [scriptish/scriptish#184]
It is this simple.. firefox version 24.0(-1) on arch linux(scriptish version 0.1.11)

```
// ==UserScript==
// @name                exceedingly_simple
// @namespace           exceedingly_simple
// @description         so simple, it aughto work, right?
// @include     *
// ==/UserScript==

alert('start with little');
document.body.innerHTML = "works";
```

I left the preferences settings of the thing blank. Afaics it should always run, but instead it just runs on local files, the add-ons manager, and sporadically, for no apparent reason.(If it happens again i'll try report.)

I couldnd find any existing issue in the faq. Not sure if addons can interact much, but i have [bym 1.9.7](https://addons.mozilla.org/en-US/firefox/addon/blank-your-monitor-easy-readin/?src=search), flashblock 1.5.17, https-everywhere 3.4.1, Noscript 2.6.6.7(from the archlinux package db), smart referrer 0.0.11, i tried disabling some of them, it didnt change anything.

Sorry that this bug is a bit 'doesnt seem to work for me'-like, anything info i could get at and return?

Edit: youtube-videos are triggering the script now, but `document.body.innerHTML` isnt replaced
Edit2: http://www.thingiverse.com/thing:30951 triggers the script, i bookmarked http://www.thingiverse.com/thing:42112 as triggering it but now it doesnt.. Disabled https-everywhere and bym, didnt seem to have any effect.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
