### ISSUE TITLE
Disabling script caching will not actually save memory

### ISSUE THREAD

**Issue by nmaier** [scriptish/scriptish#185]
Script caching was turned off in 691b65821d71b7318dbd83146885168816bbcef1, giving memory consumption as the primary reason.

However, the script is still kept in memory:
https://github.com/scriptish/scriptish/blob/6dfd6b03bcbb377aa2fd515b686d288f2fc6af25/extension/modules/script/cachedresource.js#L21

Also, since this was "broken" for ages, but nobody complained about memory use, I suggest toggling the pref default to `true`.

**Comment by nmaier** [comment]
It was never my intension to conserve memory when I originally wrote the stuff. Always setting the property was a bad idea, anyway. ac7f143045f5cb52c1e580ba27c8f30c4a8512db fixed that.

I'd still like to get some input on the default `true` part. @erikvold @supahgreg

**Comment by erikvold** [comment]
@nmaier I'm ok with setting the pref to `true`

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
