### ISSUE TITLE
Secure Updates Fail Unless 'Require user scripts to update using HTTPS' is Unchecked

### ISSUE THREAD

**Issue by bengrosser** [scriptish/scriptish#186]
Given a userscript that has a valid updateURL line, such as:

@updateURL https://somewhere.com/userscript.meta.js

I'm finding that the update only works if the Scriptish option 'Require user scripts to update using HTTPS' is unchecked. With this option checked, Scriptish properly detects when there is an update and tries to download it, but fails saying 'There was an error downloading [scriptname]'. The Firefox console shows a GET request pointing to the correct file over https, and the file can indeed be downloaded over https.

I would expect that with the 'Require user scripts to update using HTTPS' option _checked_ that an @updateURL that points to a valid https location would work.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
