### ISSUE TITLE
GM_registerMenuCommand within command function kills whole menu

### ISSUE THREAD

**Issue by vanowm** [scriptish/scriptish#187]
Attempt register a new command within a function of previous command kills whole scriptish menu with no errors in the console:

``` Javascript
function testFunc()
{
    GM_unregisterMenuCommand(UUID);
    UUID = GM_registerMenuCommand("new test " + (new Date()).getSeconds(), testFunc);
}
var UUID = GM_registerMenuCommand("test", testFunc);
```

Once menu was "killed" the only way to restore it is right click on scriptish icon.

This can be avoided by using setTimeout:

``` Javascript
function testFunc()
{
    GM_unregisterMenuCommand(UUID);
    setTimeout(function() UUID = GM_registerMenuCommand("new test " + (new Date()).getSeconds(), testFunc), 0);
}
var UUID = GM_registerMenuCommand("test", testFunc);
```

Firefox v24
Scriptish v0.1.11

Scriptish icon is at the add-on bar

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
