### ISSUE TITLE
GM_setValue size issue

### ISSUE THREAD

**Issue by azu** [scriptish/scriptish#189]
`GM_setValue` get less able to setting big values(> 4kb).

Currently, max pref size is [MAX_PREF_LENGTH = 1 \* 1024 \* 1024](http://mxr.mozilla.org/mozilla-central/ident?i=MAX_PREF_LENGTH)
- https://bugzilla.mozilla.org/show_bug.cgi?id=872981
- https://blog.mozilla.org/addons/2013/09/03/compatibility-for-firefox-24/
- https://github.com/greasemonkey/greasemonkey/issues/1798

**Comment by erikvold** [comment]
I don't see any reason to make a change here, if a userscript goes over the new limit, then they there will be an error message.  That seems fine to me.  Taking the action that Greasemonkey did to create a separate storage seems too drastic to me atm.  I'd rather continue using about:config prefs that can easily sync'd
