### ISSUE TITLE
Import Scripts doesn't work (no scriptish-config.json entries created)

### ISSUE THREAD

**Issue by MysteryIII** [scriptish/scriptish#190]
As mentioned in the Wiki, all you have to do to import an userscript is to add the script into the folder scriptish and delete the "scriptish-config.json". After this start Firefox and a new file should be created with the entry of the script.
But the new created file has never userscript entries! 
Tested with different (also new Firefox profiles) on different computers.
Please fix it or add a new import option to the settings.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
