### ISSUE TITLE
Add option to go to script homepage

### ISSUE THREAD

**Issue by Zheitk** [scriptish/scriptish#195]
I've had problems finding the correct homepage to some user scripts with similar names. It will be better to have an option to go there directly.

Some ideas:
 1) a button with options (edit, about, uninstall, etc...) at the right of every script in the drop-down tool-bar button
 2) a context-menu option in script manager (add-ons) page

If the script doesn't have a home url, the extension can keep the url from wich the userjs was installed ñ_ñ

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
