### ISSUE TITLE
@grant auto and @domain auto

### ISSUE THREAD

**Issue by KOLANICH** [scriptish/scriptish#196]
The idea is to determine automatically the permissions the script needs (for example finding all the matches for  /GM_\w+/g in all files which can contain JS (all the resources with js extension)) and then restrict it with them. This will prevent userscript from performing the actions user don't expect from it (the code which is hidden in obfuscated code or in downloadable code or in images or somewhere else).

This pref should be enabled manually by script author who want to add more trust to his script.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
