### ISSUE TITLE
Scriptish button excessive margin

### ISSUE THREAD

**Issue by supahgreg** [scriptish/scriptish#199]
Under `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0` the Scriptish button is taking up way too much space.

![scriptish_button_margin](https://f.cloud.github.com/assets/288958/2004694/ad5bb894-86bb-11e3-844a-9ea3816b9474.png)

**Comment by supahgreg** [comment]
Looks like this is happening due to the `toolbarbutton#scriptish-button` type being switched from "menu-button" to "menu" (see [99b89aa](/scriptish/scriptish/commit/99b89aaa32914f3e7ca550c10d93a5f5304e4894#diff-48670c4de56dacc9b7cb3f773858ee05L47)).

**Comment by erikvold** [comment]
@supahgreg how is this now?

**Comment by erikvold** [comment]
After 39f4b718e0594d1184e9b21dce95adaf96843312

**Comment by supahgreg** [comment]
It's fine
