### ISSUE TITLE
@resource undefined error

### ISSUE THREAD

**Issue by 0rt** [scriptish/scriptish#2]
error when I try to installed a script containing a // @Resource , said:

Error installing user script, fail to retrieve @Resource 'http://mcpub.googlecode.com/files/2dgal_shutUp_Build_1.2.6.js' (undefined)

**Comment by supahgreg** [comment]
Please be sure to provide the info on [this wiki page](https://github.com/scriptish/scriptish/wiki/How-To%3A-Submit-a-bug%2C-issue%2C-or-feature-request).

I'm able to reproduce this by clicking on the ".user.js" link @ http://code.google.com/p/mcpub/downloads/detail?name=shutUp_Build_1.2.6.user.js&can=2&q=

Is that what you were doing?

**Comment by supahgreg** [comment]
Okay, the userscript did not name the `@resource` in the metadata block, which is making things blow up.

``` javascript
// @resource  http://mcpub.googlecode.com/files/2dgal_shutUp_Build_1.2.6.js
```

should be changed to

``` javascript
// @resource  zipGal  https://mcpub.googlecode.com/files/2dgal_shutUp_Build_1.2.6.js
```

Reference:  [Manual: Metadata Block](https://github.com/scriptish/scriptish/wiki/Manual:-Metadata-Block)
