### ISSUE TITLE
Broken in Nightly (Add-on SDK)

### ISSUE THREAD

**Issue by supahgreg** [scriptish/scriptish#200]
[modules/constants.js](https://github.com/scriptish/scriptish/blob/master/extension/modules/constants.js#L165) requires [sdk/system/globals.js](https://github.com/mozilla/addon-sdk/blob/master/lib/sdk/system/globals.js#L13) which requires [sdk/system.js](https://github.com/mozilla/addon-sdk/blob/master/lib/sdk/system.js#L15) which causes the following:

`System JS : ERROR resource://gre/modules/commonjs/sdk/system.js:15 - Error: Module `@test/options` is not found at resource://gre/modules/commonjs/@test/options.js`

Replacing `const jpGlobals = jetpack('sdk/system/globals')` line with a stub (`const jpGlobals = {};`) got things working, but of course isn't a fix.

Likely related to mozilla/addon-sdk@3117486febbdf7f1e19f832380a7ba456e699591 ( http://hg.mozilla.org/mozilla-central/rev/4de8fc843d5e )

`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:30.0) Gecko/20100101 Firefox/30.0`

**Comment by erikvold** [comment]
should be ok now, that commit was reverted.
