### ISSUE TITLE
@exclude does not match if url contains specific chars (_/)

### ISSUE THREAD

**Issue by SchreinerK** [scriptish/scriptish#204]
assuming location is:
https://apis.google.com/_/+1/fastbutton?usegapi=1&width=120&annotation=inline...

The script will not be exluded if using e.g.:
// @exclude   https://apis.google.com/_/+1/*
-or-
// @exclude   https://apis.google.com/_/*

without the trailing slash, the script will be excluded
// @exclude   https://apis.google.com/_*

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
