### ISSUE TITLE
Script update fails with scriptish

### ISSUE THREAD

**Issue by Owyn** [scriptish/scriptish#205]
Script update fails with scriptish. Works fine with GreaseMonkey and TamperMonkey.
http://userscripts.org/scripts/source/166494.user.js - script
http://userscripts.org/topics/208709?page=1#posts-609163 - problem

**Comment by alexolog** [comment]
The problem manifests itself with the Handy Just Image script (https://userscripts.org/scripts/show/166494)

1) Scriptish always thinks that an update is available, even immediately after reinstalling the latest version.

2) Trying to update, results in "There was an error downloading Handy Image" error message.

**Comment by alexolog** [comment]
Seems to be duplicate of #186

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
