### ISSUE TITLE
Firefox 28, Userscripts and Content Scope Functions

### ISSUE THREAD

**Issue by erosman** [scriptish/scriptish#206]
Hi

I originally posted this issue to GreaseMonkey. The issue was also raised over a month ago but there has been no response.
I hope there is more response here. Hopefully, if Scriptish fixes the issue, I will be changing over to Scriptish.

Today, I upgraded to Firefox 28 (win7) and some of my scripts stopped working.

Certain JS functions in userscripts will no longer run if JavaScript is disabled on the site/page.

Examples are: 
addEventListener
dispatchEvent
dispatchEvent
setTimeout
setInterval
clearInterval
requestAnimationFrame
MutationObserver??

Being forced to enable JavaScript on some pages (great benefit to ad-companies & ad-sellers), will enable sites to include JS script to counteract userscripts scripts. That in turn would render userscripts obsolete under certain circumstances.

As a suggestion, userscripts could implement native functions such as GM_setTimeout or GM_delay

If anyone has any alternative idea for the above functions, please share.

All feedbacks & suggestions are welcomed

:)

**Comment by erikvold** [comment]
is this still an issue?

**Comment by erosman** [comment]
It went away with the changes in NoScript 2.6.8.19 March 24, 2014

Also: https://bugzilla.mozilla.org/show_bug.cgi?id=986886#c4

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
