### ISSUE TITLE
Add an API to let the userscript know which @include/@match has matched the website, allow to capture part of it using Regex

### ISSUE THREAD

**Issue by devnoname120** [scriptish/scriptish#207]
Hello,

I have a few suggestions regarding the API of Scriptish.
Some scripts like NoPicAds (http://userscripts.org/scripts/show/154858, https://github.com/legnaleurc/nopicads) are meant for a lot a of different websites and thus work using rules.

However, to apply a certain rule, we need to know which website was matched.
That's why there is the following dummy @include. We then match the websites ourselves in the script:

``` javascript
// @include        http://*
// @include        https://*
```

This is meaningless but necessary, since websites are anyway matched in the script itself (if we add some proper @include, websites will need to be matched twice, making it slower).
So it would be great to add a function or a global array returning the index of the matched rule, and the content of it.

Moreover, sometimes, we need to capture a part of a URL.
It happens that URLs contain some valuable information that we need to capture.
For instance, if a website redirects to another, but we want to skip the redirection:
http://annoy.ing/ad/website/example.org

A way would be to use a Regex the following way:

``` javascript
// @include /^http:\/\/annoy\.ing\/ad\/website\/(.*)$/
// @grant GM_getMatchedRules

// An array containing information about all rules that were matched
var matchedRules = GM_getMatchedRules();

// The number of matched rules (can be >1 when we have multiple @include)
var numberMatchedRules = matchedRules.length;

// Get the first matched rule
var firstMatchedRule = matchedRules[0];

// Get the rawRule, in our example it would be /^http:\/\/annoy\.ing\/ad\/website\/(.*)$/
var rawRule = firstMatchedRule.raw;

// Get the matched patterns if any (in our example, it would be an array with only one row and one column, containing "example.org")
var matchedText = firstMatchedRule.matchedText;

// We can then for example redirect to this URL
document.location.href = matchedText;
```

This kind of API would benefit greatly to many userscripts,
thank you for implementing it!

**Comment by jerone** [comment]
What's wrong with matching regex to the `location` object?

**Comment by devnoname120** [comment]
This means that it is matched twice and therefore affects performances negatively:
- the website is first matched by Scriptish to know whether the script should be ran on the website or not
- the website address is then matched by the script to know which rule should be used and capture a part of the address

In my example, the performances improvement is minimal, yet for larger scripts like NoPicAds, it would make a decisive difference (because this script matches about 400 different websites).

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
