### ISSUE TITLE
GM_openInTab returns 'undefined'

### ISSUE THREAD

**Issue by CrimsonVex** [scriptish/scriptish#213]
On many websites online this issue is documented, and I don't see it in the open/closed issue list. I believe it to be a fairly core problem affecting many users and foiling cross compatibility.

var w = GM_openInTab(someurl);

The above always returns w as 'undefined', whereas under greasemonkey/tamper etc it doesn't. Am I wrong in flagging this issue?

window.open will return a window object, and yet GM_openInTab won't?

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
