### ISSUE TITLE
Request MidClick on Script menuitem to uninstall

### ISSUE THREAD

**Issue by BarbieBarb** [scriptish/scriptish#214]
Thankyou for Scriptish.

● So many scripts I am not sure if I want them and just test them out to see if it suits my needs. But many times it is not what I was looking for or it does not work and I am needing to uninstall.
I would like to be able to MidClick on a script menuitem and have it UNinstall, with a prompt "Are you sure you want to uninstall".

● It is so much bother to have to open AddonsManager, select Userscripts Category, wait for all the scripts to load, and then search through the list to find the particular script to uninstall, then go back to the website I was on.

Please and thankyou.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
