### ISSUE TITLE
Request - Access to all scripts in the menu

### ISSUE THREAD

**Issue by BarbieBarb** [scriptish/scriptish#215]
Thankyou for Scriptish.

Sometimes I am on a website that I decide it would be good to include into a particular script. But because that website is not included into the script, it does not appear in the menu from the toolbarbutton in the statusbar.
So I have to go to a website that is already included into the script so that I can get access to the Script Edit, or I have to go to Addons Manager, Select Userscripts, Scroll down to find the script and edit from there just to add an included website.
Then go back to the previous website.

➜Could you please add to the toolbarbutton menu a menuitem that will display a list of all userscripts menuitems in which I can click on to access the edit?
Then I could quickly add the website I am on to include it, reload the page, and now I have the script functioning on that page.
Please and thankyou.

**Comment by jerone** [comment]
If I'm correct XUL allows to add an button to a list-item. If that's true, one could do something like this to add a button to open the script options: 
![scriptish](https://cloud.githubusercontent.com/assets/55841/2630530/2e4401f2-be4b-11e3-90fb-47d2898d4105.jpg)

**Comment by BarbieBarb** [comment]
Thankyou for response.
But **that would not solve the problem that I am having**.

● If I am on a website that does not include that website in the script... then those scripts would not appear in the toolbarbutton menu.

**EXAMPLE:**
I am on startpage.com and want to add it into script.
//@include  http://startpage.com/*
But the script does not appear in the toolbarbutton menu because I am on startpage.com and that is not included into the script.
The script has included into it google.com
//@include  http://google.com/*

● So in order to get access to the script I have to go to google.com for the script to appear in the toolbarbutton  menu, so that I can access it and add 
//@include  http://startpage.com/*.
Or as I explained above... I have to go to Addons Manager, Select Userscripts and wait for it all to load, Scroll down to find the particular script and edit from there to add startpage.com.

● Those buttons added to the list-item is no different than rightclicking on the menuitem to get to edit.

● Needs a menuitem "All Scripts" with dropdown arrow that will show all scripts, then you can rightclick on particular one to get to the edit of that script.

Thankyou.

**Comment by erikvold** [comment]
I'd like to design a panel menu for Scriptish which would be used instead of the menu list.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
