### ISSUE TITLE
Request - Addons Manager Standalone Option

### ISSUE THREAD

**Issue by BarbieBarb** [scriptish/scriptish#216]
Thankyou for Scriptish.

The old versions of Greasemonkey had the "Scripts Manager in a Standalone" that was great with easy quick access.
Could Scriptish please add that same type of "Script Manager Standalone" as another choice as well as keep the present "integrated with the AddonsManager" system.

With the AddonsManager you must go to a new tab, or lose the page you were already on, and it opens with the Extensions Catergory that you must wait to load, then click on the Userscripts Category and wait for that to load.
A whole lot of wasted time.
A popup Standalone would be a much quicker process and you do not lose the page you are already on.

Stylish-Custom firefox addon has developed a Standalone Manager for Stylish styles and it is great.

Please and thankyou.

`test button`

> quote

``` ruby````

test 
grey
 background

```

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
