### ISSUE TITLE
Prevents access to http://userscripts.org:8080

### ISSUE THREAD

**Issue by alexolog** [scriptish/scriptish#219]
userscripts.org is currently inaccessible.
http://userscripts.org:8080 can be used instead
But scriptish hijacks the url and forcefully changes it to https, which does not work on those pages.

**Comment by Black-Sunlight** [comment]
Confirm, "ssl_error_rx_record_too_long"
i think it's because of #161 
@erikvold can you please look at this problem, the site seems will use 8080 a long time

**Comment by Black-Sunlight** [comment]
I temporary added an additional check for myself in file: modules\commonjs\uso-redirector.js

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
