### ISSUE TITLE
Set Accept header when checking for updates

### ISSUE THREAD

**Issue by sizzlemctwizzle** [scriptish/scriptish#220]
Since every other user script engine with an updater supports greasemonkey/greasemonkey#1824, it'd be nice if Scriptish would do the same.

Refs:
http://tampermonkey.net/changelog.php?version=3.7.3900&ext=gcal#v3.7.3900
gera2ld/Violentmonkey#2

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
