### ISSUE TITLE
Default to using original URL for updates if nothing specifies otherwise

### ISSUE THREAD

**Issue by JasonBarnabe** [scriptish/scriptish#221]
On Greasy Fork, I don't include update or download URLs in the scripts. This is because Greasemonkey will use the URL the script is downloaded from for updates if these aren't present, which suits me just fine. Tampermonkey in v3.7.48 has the same behaviour.

I understand that Scriptish has an option for this - "Use download URL for updates if there is no update URL", but it's off by default and ["doesn't seem to work reliably"](https://greasyfork.org/forum/discussion/156/script-updates/p1). I'm wondering if these could be made the default and "reliable".

**Comment by sizzlemctwizzle** [comment]
+1 for this change. #232 would be useless without out it since Scriptish wouldn't even know where to check for updates.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
