### ISSUE TITLE
Better GM compatibility

### ISSUE THREAD

**Issue by alexolog** [scriptish/scriptish#228]
Like it or not, most script writers use GM and only a small fraction are willing to address incompatibilities with Scriptish.

Scriptish is first and foremost a platform to run scripts on and therefore should be able to run as many of those as possible without problems.  Therefore it should be as compatible to the most popular script platform (currently Greasemonkey) as practically possible.  It does not matter how theoretically "better" Scriptish is if it cannot correctly run the scripts that people want.

Currently there are several GM APIs that Scriptish either does not implement or implements differently from GM, which causes problems with scripts.
One notable example is GM_info, which is not implemented at all.
Another is GM_registerMenuCommand, which does not work in an iFrame (whereas it does with GM).
Yet another is the treatment of @grant directives and so on...

The main page of the Wiki says: "Everything Greasemonkey offers (which is actually useful)"
Please make it true.

**Comment by brunoais** [comment]
I think it would be more productive is you were to enumerate all of those :S. As a programmer and developer myself. That's what I would ask.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
