### ISSUE TITLE
Support for Greasy Fork AutoUpdate 

### ISSUE THREAD

**Issue by NR2014** [scriptish/scriptish#230]
Is there anyway we can make scriptish to display the URL link to those scripts installed from greasyfork ? And also make t possible to search for updates, since now Userscript is dead ?

**Comment by SlimShayD** [comment]
Agreed.

**Comment by wenketel** [comment]
[Default to using original URL for updates if nothing specifies otherwise #221 ](https://github.com/scriptish/scriptish/issues/221)

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
