### ISSUE TITLE
unsafeWindow is not defined (FF30+)

### ISSUE THREAD

**Issue by vanowm** [scriptish/scriptish#233]
Since FF30 unsafeWindow is no longer working without using @grant
This issue is related to #203, #209, and #231

The work around is to use 

```
// @grant unsafeWindow
```

But this means we have to modify every single script that uses unsafeWindow

**Comment by vanowm** [comment]
The provided workaround is not 100% working. Some scripts for whatever reason still get:

```
Scriptish access violation: unsafeWindow cannot call - GM_getValue by resource://services-common/async.js
```

Others work fine.

**Comment by Mark2834** [comment]
Try Scriptish v0.1.12 #239

**Comment by vanowm** [comment]
I'm testing it on v0.1.13pre

**Comment by brunoais** [comment]
Any updates here?

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
