### ISSUE TITLE
GM_getMetadata() is always undefined

### ISSUE THREAD

**Issue by foudfou** [scriptish/scriptish#237]
Hi,
tried with `@grant GM_getMetadata()` also.
I'm not sure when it broke.
I'm using scriptish 0.1.11, firefox 30.0.
Cheers

**Comment by Mark2834** [comment]
You need Scriptish v0.1.12 to fix `undefined` errors with Firefox 30
@grant was implemented in v0.1.12 see my post #239 on how to install it
and it's `@grant GM_getMetadata` without the `()`

**Comment by foudfou** [comment]
Thanks @Mark2834 for your answer. I actually had, and have just, tested v0.1.12, with `@grant GM_getMetadata`. Unfortunately, the problem is worse because `GM_getMetadata` itself is just `undefined`.
There seem to be quite some complains about `GM_` functions not working anymore BTW: #231, #203, #238 maybe...

**Comment by KOLANICH** [comment]
@nmaier , I use latest Scriptish (from this repo), but this error is stil occuring.
`TypeError: GM_getMetadata(...) is undefined
1> JS frame :: resource://scriptish/utils/Scriptish_evalInSandbox.js :: Scriptish_evalInSandbox :: line 79
2> JS frame :: resource://scriptish/utils/Scriptish_injectScripts.js :: Scriptish_injectScripts :: line 120
3> JS frame :: resource://scriptish/manager.js :: Scriptish_manager<.docReady/</listener/< :: line 141
4> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js :: notify :: line 40
5> native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
file:///C:/Users/******/AppData/Roaming/Mozilla/Firefox/Profiles/*********.default/scriptish_scripts/*********/************.user.js
Line 90`

**Comment by Mark2834** [comment]
@KOLANICH What version of FF and Scriptish are you using?

**Comment by KOLANICH** [comment]
Latest ones. I have found the problem: as all the keys are lowercase (I dont think that it is right), GM_getMetadata() should internally call .toLowerCase(), but it doesn't.

**Comment by foudfou** [comment]
Sorry but I can't make it work with Scriptish 0.1.11, FF 33.0.2. Considering @KOLANICH's findings, I tried different keys ("Name", "NAME"), without success.
[Examples shown in the wiki](/scriptish/scriptish/wiki/GM_getMetadata) do not work. Please re-open this issue.

**Comment by Mark2834** [comment]
Scriptish 1.1.13 and FF 32.0.2

The following called discretely, output in Firebug as expected;

``` javascript
unsafeWindow.console.log(GM_getMetadata());
unsafeWindow.console.log(GM_getMetadata('name'));
```

The following I can't get to work.  Whilst `typeof headers` is an object, it seems impossible to discretely enumerate properties.  I tried `Object.keys()` and `Object.getOwnPropertyNames()` without success.  `headers['name']` is undefined, should it be?

``` javascript
var headers = GM_getMetadata();
for (props in headers){
    unsafeWindow.console.log(props);
}
```

Oh well anyway, that's my findings.

**Comment by KOLANICH** [comment]
``` javascript
// ==UserScript==
// @id          test
// @name        test_test
// @version     1.0
// @namespace   test
// @author      
// @description gfyghcvhjvhj
// @include     *
// @run-at      document-end
// @magic       [46, 99, 26, 56, 14, 18, 9, 12, 17, 43, 11, 4]
// ==/UserScript==
const mo=GM_getMetadata("magic")[0];
console.log(mo);//"[test]" undefined

```
