### ISSUE TITLE
What's wrong with v0.1.12

### ISSUE THREAD

**Issue by Mark2834** [scriptish/scriptish#239]
Why is Scriptish v0.1.12 hidden and not available as an automatic update through the Add-ons system?

Browse to the secret location to find it.
https://addons.mozilla.org/en-US/firefox/addon/scriptish/versions/

And then Mozilla warns against installing it.
This problem is almost two months old!!

**Comment by Mark2834** [comment]
Does Mozilla have something against Scriptish?

FireFox 30.0 Developer > Get More Tools menu.
A selection of add-ons that includes Greasemonkey but not Scriptish.

_Web Developer's Toolbox_
by Mozilla 
https://addons.mozilla.org/en-US/firefox/collections/mozilla/webdeveloper/

**Comment by Keridos** [comment]
Scriptish does not work good in FF30, many scripts are broken.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
