### ISSUE TITLE
include and exclude pages in settings dialog script.

### ISSUE THREAD

**Issue by trup** [scriptish/scriptish#243]
when i install script https://userstyles.org/styles/userjs/101141/RU%20AdList%20CSS%20Fixes.user.js through greasemonkey, greasemonkey automatically adds the \* in the field include pages in the settings dialog script.
Scriptish nightly - 2014-05-11 20:00 does not do this automatically, and the script does not work.

sorry for bad english :)

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
