### ISSUE TITLE
@require needs error checking on file:/// scheme

### ISSUE THREAD

**Issue by Mark2834** [scriptish/scriptish#244]
During re/install of a script, if the @require https:// link is broken Scriptish produces an error message  something like this `Error! Server returned: nothing (timed out)`
But if the scheme is file:/// and the url is broken then Scriptish creates an empty file of the name of the file it should have imported and doesn't say anything more about the problem.
Could you please add some error checking there, thanks.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
