### ISSUE TITLE
GM_xmlhttprequest is broken in Firefox 32+

### ISSUE THREAD

**Issue by 0rt** [scriptish/scriptish#246]
Scripts with gm_xhr stop function, no error is thrown

**Comment by 0rt** [comment]
It's first happened in Firefox Nightly 20140607's nightly build
Greasemonkey is broken too.

**Comment by YePpHa** [comment]
The reason Greasemonkey didn't work is discussed here and the author has already fixed it in a nightly version of Greasemonkey (https://bugzilla.mozilla.org/show_bug.cgi?id=1022208).

To fix this issue in Scriptish the `Cu.waiveXrays` function needs to be used to make it possible to use call functions origination from the userscripts. So in `/extension/modules/api/GM_xmlhttpRequester.js` a new line should be added just below line 96 with the following code:

``` JavaScript
details = Cu.waiveXrays(details);
```

**Comment by 0rt** [comment]
``` javascript
GM_xmlhttpRequester.prototype.contentStartRequest = function(details) {
    details = Cu.waiveXrays(details);

  try {
```

like this? Still not work here

**Comment by YePpHa** [comment]
That should make the detail.onload, detail.onerror, and etc to be callable from the addon scope. Though it's possible that there could be something else that got broken too. I can try to clone this and see if I can get it to work.

**Comment by 0rt** [comment]
.... This gm_xhr script still not work here after I modified the file as you commit.

``` javascript
// ==UserScript==
// @name           test GM_xhr
// @version        0.0.1
// @namespace      test@GM_xhr
// @include        http*
// @run-at         document-end
// @grant GM_xmlhttpRequest 
// ==/UserScript==
var ret = GM_xmlhttpRequest({
  method: "GET",
  url: "http://www.google.com",
  onload: function(res) {
    console.log(res.responseText);
  }
});
```

**Comment by YePpHa** [comment]
Hmm. That is weird because it works on my end with Firefox Nightly v33.0a1 (2014-07-13) with your example userscript. It returns:

```
"[testGM_xhr@test@GM_xhr]" "<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-DK"><head><meta content="/logos/doodles/2014/world-cup-2014-final-5652783105572864-hp.jpg" itemprop="image"><meta content="/images/google_favicon_128.png" itemprop="image"><title>Google</title>   <script>(function(){
window.google={kEI:"GZ7CU7TwFqf-4QSA8YCQBw",getEI:function(a){for(var c;a&&(!a.getAttribute||!(c=a.getAttribute("eid")));)a=a.parentNode;return c||google.kEI},https:function(){return"https:"==window.location.protocol},kEXPI:"4791,17259,4000116,4007661,4008142,4009033,4009641,4010077,4010806,4010858,4010899,4011228,4011258,4011679,4012373,4012504,4013395,4013414,4013591,4013723,4013787,4013823,4013967,4013979,4014016,4014093,4014431,4014515,4014636,4014671,4014805,4014991,4015234,4015236,4015260,4015266,4015550,4015587,4015633,4015772,4016127,4016309,4016367,4016372,4016487,4016824,4016855,4016976,4017162,4017204,4017280,4017285,4017544,4017554,4017578,4017595,4017596,4017612,4017639,4017659,401"[…] testgm_xhr@test@gm_xhr.user.js:13
```

in the console for me when I run it.

**Comment by 0rt** [comment]
I am using Nightly on Windows 8.
Just cloned you git and built a XPI, still no good. Nothing was showed in the console..

**Comment by YePpHa** [comment]
I am also used Nightly on Windows 8. It should output something to the console. If you already didn't know Firefox have two consoles. One for the web page and the other for everything. You should take a look at the second console, which can be opened by pressing `CTRL + SHIFT + J`. I did also check the console for the web page and it didn't appear there.

**Comment by 0rt** [comment]
Ok, now I can see the log. It should be fixed, right? same "console.log" throw message to different console...

And, my script still not work, because Scriptish fails in setting a referer http header.

**Comment by YePpHa** [comment]
Yes, `GM_xmlhttpRequest` should be fixed with `waiveXrays`.

**Comment by 0rt** [comment]
``` javascript
// ==UserScript==
// @name           test GM_xhr
// @version        0.0.1
// @namespace      test@GM_xhr
// @include        http*
// @include        file*
// @run-at         document-end
// @grant GM_xmlhttpRequest 
// ==/UserScript==
var ret = GM_xmlhttpRequest({
  method: "GET",
  url: "http://www.google.com",
  headers:{referer:"www.foo.com"},
  onload: function(res) {
    console.log(res.responseText);
  }
});
```

Scriptish seems to ignore the headers setting, and GM is fine. I can see the different in Browser Toolbox's network panel. Is it related to this bug?

**Comment by YePpHa** [comment]
I highly doubt it. The issue was that `GM_xmlhttpRequest` uses callbacks to deliver the response. In Firefox 32+, Mozilla changed something so that functions were not available if you didn't call `waiveXrays` (took me quite some time to figure this out).

So when you submitted the details object

``` JavaScript
method: "GET",
url: "http://www.google.com",
onload: function(res) {
  console.log(res.responseText);
}
```

the `onload` function got stripped so that Scriptish only got

```
method: "GET",
url: "http://www.google.com",
onload: undefined
```

This caused the `xmlhttpRequest` to be called and it also did the job, but it didn't have anywhere to deliver the response to. So by adding `waiveXrays` the `onload` function didn't get stripped.

I would think that one of the Firefox updates broke another part of Scriptish, which Greasemonkey has already fixed (or the Greasemonkey implementation were just better).

**Comment by 0rt** [comment]
Well, I don't understand how exactly Scriptish works, here are some observation for the record:
1. GM_xhr is broken in Nightly because the onload is broken, the request part is fine.
2. YePpHa's https://github.com/scriptish/scriptish/commit/4bbff73fe1b40c36aa13db3f9cc894d7f9ce93e5 fix somehow make the onload works, but will break {headers} objects setting, Scriptish will ignore it.
