### ISSUE TITLE
Scripts don't work in page which is opened in new tab like target="_blank"

### ISSUE THREAD

**Issue by 0rt** [scriptish/scriptish#249]
It is similar to issue #18 . A local test:
Page:

``` html
<html>
<body>
<a href="#" target="_blank"> click me to open the same page in new tab</a>
</body>
</html>
```

Userscript:

``` javascript
// ==UserScript==
// @id             test@userscript.org
// @name           Check Run
// @namespace      test@userscript.org
// @include        http*
// @include        file*
// @run-at         document-end
// ==/UserScript==
var el = document.createElement('p');
el.innerHTML = 'inssssssserted';
document.body.appendChild(el);
```

Test with Scriptish 20140715 nightly and Firefox 31

**Comment by 0rt** [comment]
This probably a duplication of Issue #242 .
It's quite critical, please fix it with high priority, I mean, when you guys have time :)

**Comment by gear54rus** [comment]
Bump. FF 32 with scriptish-nightly-2014-07-15-1600. Any W/A available?

**Comment by Mark2834** [comment]
Bump from me too please
Issue #240 was a work-a-round to this very old bug, but now the work-a-round doesn't work either.  So we have bugs upon bugs.

**Comment by Mark2834** [comment]
See issue #240 for a work-a-round, seems to be working again.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
