### ISSUE TITLE
Script doesn't run with firebug

### ISSUE THREAD

**Issue by zygzagZ** [scriptish/scriptish#250]
So basically i have 4 scripts supposed to run on one page. One of them is disabled.
Three scripts (enabled ones) normally work as excepted until i load up firebug.
Then one of them stops working. In scriptish menu i see tick next to his name, it's not disabled, yet it isn't ran. On the very first line of it it's got console.log command, which doesn't show up in output. When i close firebug window nothing happens, but after i clear firebug's activation list script comes back to work.
I'm on scriptish 0.1.12, FF 32.0 beta channel (build id 20140722195627) running on windows 8.1.
Firebug's version is 2.0.2.
I came to conclusion that disabling console panel in firebug allows the script to run. When i enable console panel, it doesn't run.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
