### ISSUE TITLE
Scripts cannot be installed when using e10s Window/Nightly

### ISSUE THREAD

**Issue by Radagast** [scriptish/scriptish#252]
When using Scriptish with Nightly, script installation fails. The script page loads but the installation dialogue is not displayed. Reverting to a standard, non-e10s, window scripts can be installed. 

Someone else reported the issue [Bug 1041137](https://bugzilla.mozilla.org/show_bug.cgi?id=1041137)

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
