### ISSUE TITLE
Ping Developers - Is Scriptish actively developed / supported - be honest?

### ISSUE THREAD

**Issue by Mark2834** [scriptish/scriptish#254]
We need an honest answer here because there are so many outstanding issues that haven't been dealt with in months.

This add-on was once at the cutting edge.

Now, you can't even get the most recent version on Firefox Add-ons site, how do you think people will support this software?
I have to use the nightly builds to have a working version now.

**Comment by Enkidu70** [comment]
I fully agree with Mark! It seems like Scriptish is dead!? Or isn't it?

Well, personally speaking I currently can live with it because I changed to www.palemoon.org a while ago because I hate Australis. But this is no solution for everybody. ;)

**Comment by SamB** [comment]
Ping?

**Comment by jerone** [comment]
Pong?

**Comment by Enkidu70** [comment]
Scriptish seems to be dead...

**Comment by Mark2834** [comment]
The project could probably do with someone or community administration.  Could we set up a means to get information about releases published, and an up to date entry point for new users.  Like get Scriptish back onto the add-ons site again.  Scriptish seems dead because we're lacking an active forward facing image of the product.  At the very least making sure releases are documented.  It wouldn't harm to have contributions from other developers to clear some/all of the long standing issues.  I don't think all of this work should weigh on Nils' shoulders, but it would help if he created the means for community support to give the project a sense of being alive.  Thanks as always for the nightly commits.

**Comment by SamB** [comment]
@Mark2834: wouldn't it be necessary to publish a new release before providing information about it?  There've been changes done throughout the ~1 year since the last one, but they're only available from github ...

**Comment by erikvold** [comment]
I'm going to archive the repo soon.

**Comment by jerone** [comment]
@erikvold After receiving 280+ e-mails about this repo, I have the feeling that you are going to archive this repo. Soon. :)
