### ISSUE TITLE
Scriptish will not work with Palemoon 25

### ISSUE THREAD

**Issue by Superbee1** [scriptish/scriptish#256]
Palemoon is splitting from Firefox and as of the newest update scriptish will no longer work in palemoon.

**Comment by Enkidu70** [comment]
Same here. Scriptish stopped working with Palemoon 25 (that is based on FF 25).
No probs with other addons, so I'd say this is a scriptish issue!

**Comment by Superbee1** [comment]
Not exactly. Palemoon started out as a stripped down twin to Firefox. There was a disagreement with the direction of the browsers a while back between the developers of both browsers. The last couple updates, Palemoon has been trying to go their own direction. In update 25 they changed their GUID making the split between the two siblings almost complete (up until that point they used the Firefox GUID). There is a list of Firefox add-ons that will no longer work with Palemoon that is growing by the day. The version numbers are not number for number. The developers at Firefox would issue an update every time they found and resolved an issue or made an improvement. The developers at Palemoon wait and fully test each update and fix bugs before they release the next version. with the Firefox version coming out first they can use that as a beta test and fix bugs that pop up before they release their update eliminating the need for the frequent updates. After rolling back to Palemoon version 24.7.2 scriptish works fine. There are 2 issues here and both parties are at fault. #1 Palemoon is changing its program to split from Firefox making unmaintained add-ons obsolete. #2 Scriptish is not keeping up with the changes.

**Comment by mindjogger** [comment]
Hello, please consider adding Pale Moon support. We do not expect a long term commitment, if the code base changes too much and your team is unwilling to support it moving forward, I'm sure people would understand.

For now however, if the current code base is compatible, please consider what I have written. Also I am only an avid fan of PM, I am not a part of their development team, as such all questions should be forwarded to them. Thanks!

See here:
http://addons.palemoon.org/firefox/incompatible/
http://forum.palemoon.org/viewtopic.php?f=44&t=5883

**Comment by nmaier** [comment]
Scriptish uses platform features not present in Gecko 25-based browsers.

**Comment by Superbee1** [comment]
so does that mean we will have to go back to using greasemonkey?

**Comment by ghost** [comment]
Hello @nmaier 

It seems you have been misinformed, Pale Moon is not based on any Gecko version. 
See here: http://forum.palemoon.org/viewtopic.php?f=24&t=6505

>  Pale Moon 25 is not based on Firefox 25. It's not based on any specific version of Firefox anymore, is an individually developed fork with a **hybrid of code from many different versions of Firefox 24 and beyond** as well as plenty of own code, and should be seen in its own right, with its own versions, based on its own release schedule and features.

If there is a missing platform feature perhaps you could tell the Pale Moon developers here: 
https://github.com/MoonchildProductions/Pale-Moon/issues

So they can work to help get Scriptish supported.

**Comment by TPS** [comment]
@scriptish @nmaier The above referenced pull (https://github.com/scriptish/scriptish/pull/269) solves this completely with no consequences other than adding a compatibility flag.  Could this be reconsidered?
