### ISSUE TITLE
unsafeWindow not working in FF 34 beta 1

### ISSUE THREAD

**Issue by jerone** [scriptish/scriptish#257]
I'm getting errors with my scripts (e.g. [Github Commit Diff](https://github.com/jerone/UserScripts/tree/master/Github_Commit_Diff) & [Github Commit Whitespace](https://github.com/jerone/UserScripts/tree/master/Github_Commit_Whitespace)) showing that `unsafeWindow` is undefined.
It worked before on FF 33 and it still works in GreaseMonkey.

`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0`

Related: https://github.com/scriptish/scriptish/issues/233

**Comment by jb0258** [comment]
I am having the same problem.
`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0`

This was mentioned in [FF bug 1043958](https://bugzilla.mozilla.org/show_bug.cgi?id=1043958). The GreaseMonkey devs fixed with this commit https://github.com/greasemonkey/greasemonkey/commit/4dd733ccb1abb7c1232950299c8f65ca72bf8875.

**Comment by jaromanda** [comment]
the following change to extension/modules/utils/Scriptish_injectScripts.js seems to fix this issue, at least, enough for my needs.

+++ b/extension/modules/utils/Scriptish_injectScripts.js
@@ -107,7 +107,8 @@ function Scriptish_injectScripts(options) {

``` javascript
     }

     if (script.grant['unsafeWindow']) {
-      sandbox.unsafeWindow = unsafeContentWin;
+      let unsafeWindowGetter = new sandbox.Function('return window.wrappedJSObject || window;');
+      Object.defineProperty(sandbox, 'unsafeWindow', {get: unsafeWindowGetter});
     }

     let delay = script.delay;
```

**Comment by Kunzol** [comment]
Same problem here ...
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by Mark2834** [comment]
@jaromanda totally what I was looking for thank you so much.  I don't know much about forking, but if someone forked Scriptish and applied the above patch would it generate an automated build of that branch?  I'm just thinking aloud here.

**Comment by ntninja** [comment]
Hi there, I tried the patch and it works perfectly! This should land soon as it affects a lot of scripts I think...

In case anybody needs it, I've uploaded a patched version of Scriptish Nightly (Scriptish nightly - 2014-11-20 12:00) here: http://xmine128.tk/gm/scriptish@erikvold.com.xpi

**Comment by Lunatrius** [comment]
Just move to Grasemonkey. At the current time it's faster than Scriptish, due to the lack of Scriptish updates. Some of the better things don't exist in GM yet, but at least it works without dirty hacks.

**Comment by jaromanda** [comment]
That snippet is a dirty hack in as much as it's **exactly** how greasmonkey fixed the same issue

**Comment by Lunatrius** [comment]
Wasn't referring to that, but the userscripts themselves. Working with Scriptish is just a hassle at this point. Not to mention the time it takes to fix the bugs (if at all).
