### ISSUE TITLE
@grant not working for Webcomic Reader

### ISSUE THREAD

**Issue by SamB** [scriptish/scriptish#259]
After upgrading from FF 24.x to 31.2.0esr, [Webcomic Reader](https://github.com/ameboide/webcomic_reader/blob/master/webcomic_reader.user.js)'s option handling stuff does not work unless I disable `@grant`.  Happens both with the Scriptish release from last year and with the latest nightly.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
