### ISSUE TITLE
question: can I run a user script under a debugger?

### ISSUE THREAD

**Issue by SamB** [scriptish/scriptish#260]
... I can't be the only one to wonder if this is possible, can I?

**Comment by gear54rus** [comment]
I'm wondering the same thing for quite a long time myself. 

Recently I wrote a pretty long script and all I used in the process was so called `var_dump` debugging :)

It would be pretty beneficial to discover how to debug these... **Anyone?**

**Comment by gear54rus** [comment]
I had limited success by using Firefox's built-in browser debugging feature: https://developer.mozilla.org/en/docs/Debugging_JavaScript 

Read starting from this:

```
devtools.chrome.enabled: true
devtools.debugger.remote-enabled: true
```

![Screenshot](https://cloud.githubusercontent.com/assets/8073599/4990941/438f6e16-69b8-11e4-9bf3-311f80f1bfce.png)

On this screenshot, you can see my userscript files being shown in browser debugger. Also, it stopped inside DOM event handler attached from within the script properly.

**However, if I were to put breakpoint in code that is run on page refresh (when script runs, e.g. line 118), it won't stop on it.**

Also, only the following workflow works:
1. Refresh page
2. Put breakpoint
3. Trigger event.

If I do:
1. Put breakpoint
2. Refresh page
3. Trigger event.

It won't stop again. Seems like page refresh disrupts breakpoints in some way and therefore, there is currently no way to debug anything except event handlers :) I hope someone can help... If not, this begs for SO question.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
