### ISSUE TITLE
GM_xmlHttpRequest onload problem

### ISSUE THREAD

**Issue by Black-Sunlight** [scriptish/scriptish#264]
In Firefox 35 beta when GM_xmlHttpRequest is in onload state the next message appears in console and 

`Security wrapper denied access to property length on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported.`
`response is undefined`

**Comment by jerone** [comment]
Related: 
https://github.com/greasemonkey/greasemonkey/issues/2033
https://bugzilla.mozilla.org/show_bug.cgi?id=1080887

**Comment by Black-Sunlight** [comment]
In bugzilla says it fixed or unrelated.

> i think this is probably unrelated. or, to be precise, the root cause is likely the same (underlying platform changes), but this bug was about problems in the SDK code, your issue could be a bug in scriptish code (which i don't even think is an SDK addon, right?)
> in any case, could you please open a separate bug, i think that would make it clearer what it refers to?

**Comment by Black-Sunlight** [comment]
So, problem is in the Scriptish code.
Access Error: unsafeWindow cannot work with: GM_getValue, GM_setValue and i think GM_xmlHttpRequest too.
About 2 month there are no updates in nightly branch, seems @erikvold have some serious problem, well we'll wait :)

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
