### ISSUE TITLE
Can't access DOM elements from user script

### ISSUE THREAD

**Issue by hesar** [scriptish/scriptish#266]
After upgrade Firefox from 33.1 version to 34.05 version my own script stopped working. I can not access   objects and properties of DOM elements
For example:
typeof unsafeWindow.jQuery == 'undefined'  throws to Firebug console TypeError: unsafeWindow.jQuery is undefined
while window.jQuery from Firebug console returns jQuery object

I checked on different machine: before upgrade Firefox to 34.05 version script was working fine. After upgrade it crashes and none of many methods I tried resolves this issue.
Any clue?
The same script in Greasmonkey works fine.
Scriptish version: 0.1.11

**Comment by jerone** [comment]
Duplicate: https://github.com/scriptish/scriptish/issues/257

**Comment by hesar** [comment]
Old issue. Solution described in duplicate thread.
