### ISSUE TITLE
GM_xmlhttpRequest and new restrictions on unsafeWindow

### ISSUE THREAD

**Issue by nunof** [scriptish/scriptish#267]
Hello,

Due to recent changes in Firefox security sandbox - https://blog.mozilla.org/addons/2014/04/10/changes-to-unsafewindow-for-the-add-on-sdk/ - it seems that GM_xmlhttpRequest has stopped working inside content-scripts.

I'm using it to circunvent same origin policy but I'm getting "Scriptish access violation: unsafeWindow cannot call: GM_xmlhttpRequest" in FF34 and Scriptish 0.1.11 (updated 18-11-2014).

I was trying to use the new APIs, namely exportFunction that IIUC should now be used (besides @grant) to enable GM_xmlhttpRequest.

I'm using it like this at the top of the script 
exportFunction(GM_xmlhttpRequest, unsafeWindow, {defineAs: "GM_xmlhttpRequest"});
but I'm getting the error "ReferenceError: exportFunction is not defined" in spite of reading in first posted link that "The real fix is to use three new APIs to share objects and functions with web content: cloneInto(), exportFunction(), and createObjectIn(). All three of these functions are made available to content scripts as globals."

Am I doing something wrong? Am I supposed to wait for a Scriptish update?

TIA,
Nuno

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
