### ISSUE TITLE
NOTHING WORKS IN FF 34.0.5 !!!!!!!!

### ISSUE THREAD

**Issue by skr4tchGr3azyMonkiBallllllZzzz** [scriptish/scriptish#268]
After upgrading to Firefox v34.0.5 from v33.1.1, all builds of Scriptish are failing. The following are the errors with the nightly build installed:

1> JS frame :: resource://scriptish/utils/Scriptish_evalInSandbox.js :: Scriptish_evalInSandbox :: line 79
2> JS frame :: resource://scriptish/utils/Scriptish_injectScripts.js :: Scriptish_injectScripts :: line 121
3> JS frame :: resource://scriptish/manager.js :: Scriptish_manager<.docReady/< :: line 111
4> JS frame :: resource://scriptish/config/config.js :: Config.prototype.initScripts :: line 439
5> JS frame :: resource://scriptish/manager.js :: Scriptish_manager<.docReady :: line 92
6> JS frame :: resource://scriptish/manager.js :: Scriptish_manager<.docReady_start :: line 69
7> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/events.js :: Observer<.observe :: line 72
8> JS frame :: chrome://jsonhandle/content/bg.js :: TracingListener.prototype.onStartRequest :: line 975
9> native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0

1> JS frame :: resource://scriptish/utils/Scriptish_evalInSandbox.js :: Scriptish_evalInSandbox :: line 79
2> JS frame :: resource://scriptish/utils/Scriptish_injectScripts.js :: Scriptish_injectScripts :: line 121
3> JS frame :: resource://scriptish/manager.js :: listener :: line 125
4> native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
JUST DIE!

**Comment by jerone** [comment]
This project seems dead. The [last commit](https://github.com/scriptish/scriptish/commit/0118d671769109dbbdfbbe9e27ce0da3dc07887a) was almost a year ago (20 Nov 2014). Won't take long until Scriptish will completely stop working: https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/ 
I suggest that you move to [GreaseMonkey](https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/).

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
