### ISSUE TITLE
GM_log function broke within an old commit.

### ISSUE THREAD

**Issue by coaster3000** [scriptish/scriptish#271]
An issue has been brought up with the GM_log function in the commit 3fcb12c28f3b89a1ec17da3675f8a7ec41221604

It causes an undefined error to occur in console.

**Comment by coaster3000** [comment]
@erikvold if you could review this submission, That would be great. It fixes a error that prevents GM_log from being used.

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
@erikvold is dead.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
