### ISSUE TITLE
GM_registerMenuCommand not working

### ISSUE THREAD

**Issue by poqdavid** [scriptish/scriptish#273]
Well i have test a simple script in both Firefox and Waterfox and also i tested that in Greasemonkey but it worked there btw i am not getting any error in console.
I also noticed the code for registering the menu it have to be like this

``` javascript
Test = {
    sayHello : function (callback) { window.alert("Hello, world!"); },
    ready : function (callback) { window.addEventListener('load', callback); },
    regCommands : function () {
    Test.ready(function () {

      var UUID = GM_registerMenuCommand('Hello, world!', Test.sayHello);

    });
  }
}

Test.regCommands();
```

**Comment by jerone** [comment]
This project seems dead. The [last commit](https://github.com/scriptish/scriptish/commit/0118d671769109dbbdfbbe9e27ce0da3dc07887a) was almost a year ago (20 Nov 2014). Won't take long until Scriptish will completely stop working: https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/ 
I suggest that you move to [GreaseMonkey](https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/).

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
