### ISSUE TITLE
Reinstalling a script erases it

### ISSUE THREAD

**Issue by GrayFace** [scriptish/scriptish#274]
I made a new script, then FireFox hung and I killed it. After restart Scriptish didn't 'remember' the script, so I went to profile/scriptish_scripts/ and dragged the script from there. Scriptish showed the usual install dialog, but with a Reinstall button. Clicking it didn't register the script as installed, instead it erased it. It's only a matter of luck that I had it open in the editor.

**Comment by GrayFace** [comment]
Correction: maybe Scriptish did 'remember' the script after restart. The script had an exact include URL without a wildcard, which may be the reason I didn't see it in the list of active scripts. The rest of the bug is relevant.

**Comment by jerone** [comment]
This project seems dead. The [last commit](https://github.com/scriptish/scriptish/commit/0118d671769109dbbdfbbe9e27ce0da3dc07887a) was almost a year ago (20 Nov 2014). I suggest that you move to [GreaseMonkey](https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/).

**Comment by GrayFace** [comment]
That's bad. I see no reason to move back, Scriptish functionality exceeds that of GreaseMonkey in every way as far as I can see. Maybe except e10s.

**Comment by jerone** [comment]
Won't take long until Scriptish will completely stop working: https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/

**Comment by GrayFace** [comment]
Eventually yes. Thinking of it, the only noticeable thing that makes Scriptish better is a combo box that allows choosing when a new script will run. The attribute it sets is supported by Greasemonkey though.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
