### ISSUE TITLE
Script not work

### ISSUE THREAD

**Issue by zszszsz** [scriptish/scriptish#275]
I can see it included in the list
run-at is document-end
when I run it from Scratchpad it works

it works well on some else's computer

so how can it just not work?

**Comment by zszszsz** [comment]
well the ff version is 43.0a2

**Comment by zszszsz** [comment]
someone see it? the script works well with greasemonkey . I am sure there are sth strange with scriptish

**Comment by Lunatrius** [comment]
The project is dead. The last commit was almost a year ago.

**Comment by jerone** [comment]
This project seems dead. The [last commit](https://github.com/scriptish/scriptish/commit/0118d671769109dbbdfbbe9e27ce0da3dc07887a) was almost a year ago (20 Nov 2014). Won't take long until Scriptish will completely stop working: https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/ 
I suggest that you move to [GreaseMonkey](https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/).

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
