### ISSUE TITLE
Not working with Multip.org

### ISSUE THREAD

**Issue by Asia81** [scriptish/scriptish#276]

**Comment by jerone** [comment]
This project seems dead. The [last commit](https://github.com/scriptish/scriptish/commit/0118d671769109dbbdfbbe9e27ce0da3dc07887a) was almost a year ago (20 Nov 2014). Won't take long until Scriptish will completely stop working: https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/ 
I suggest that you move to [GreaseMonkey](https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/).

**Comment by erikvold** [comment]
I'm going to archive the repo soon.

**Comment by jerone** [comment]
@erikvold After receiving 280+ e-mails from this repo, I have the feeling that you are going to archive this repo. Soon. :)
