### ISSUE TITLE
Отсутствие текста в контекстном меню

### ISSUE THREAD

**Issue by Magicanum** [scriptish/scriptish#277]
### Здравствуйте!

 Пожалуйста, помогите!
В контекстном меню Firefox исчез текст в строках Scriptish-команд. Присутствуют значки (иконки) Scriptish, но оба текстовых поля строк пусты.
Удаление и новая установка дополнения не принесло результата. Сброс настроек FF ничего не дало. Удаление FF, чистка реестра после этого, перезапуск системы и дальнейшая установка последней стабильной версии FF (46.0.1) также не принесло результата.
![error](https://cloud.githubusercontent.com/assets/19304686/15179341/b185a9ec-1783-11e6-8a1e-b2d6c4998187.JPG)

**Comment by pyhedgehog** [comment]
Seems project is [dead](https://github.com/scriptish/scriptish/wiki/Discontinued).

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
