### ISSUE TITLE
About "GM_addValueChangeListener" and "GM_removeValueChangeListener"

### ISSUE THREAD

**Issue by ghost** [scriptish/scriptish#278]
I don't know what it is, GOOGLE has no results.

GM_addValueChangeListener(name, function(name, old_value, new_value, remote) {})
GM_removeValueChangeListener(listener_id)

What is listener_id and does not explain.

I hope there are some examples including "function(name, old_value, new_value, remote) {}"

Thanks

**Comment by ngyikp** [comment]
AFAIK, `GM_addValueChangeListener` is only available for Tampermonkey on Chrome, and not available on Greasemonkey/Scriptish, I think you're in the wrong repo 🤔

The listener ID for `GM_removeValueChangeListener` is similar to `window.clearInterval`, calling `setInterval` will return an ID that you can keep track so if you want to stop the timer, you call `clearInterval` will that ID.

**Comment by ghost** [comment]
@ngyikp 
OH,thanks.This problem is still puzzling me.
NOW,I know the answer to this question (listener_id)!
 I saw "GM_addValueChangeListener" on the [web](https://github.com/scriptish/scriptish/wiki/Comparison-Table),so I was here to ask questions.
But I don't understand what “function(name, old_value, new_value, remote)argument ” mean.
OH， Tampermonkey API not examples,it really breaks my heart

**Comment by ngyikp** [comment]
``` js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @match        http://example.com/*
// @grant        GM_setValue
// @grant        GM_addValueChangeListener
// ==/UserScript==

GM_addValueChangeListener('test', function(name, old_value, new_value, remote) {
    console.log('name: ' + name);
    console.log('old value: ' + old_value);
    console.log('new value: ' + new_value);
    console.log('was the value change not by this page? ' + remote);
});

GM_setValue('test', Math.random());
```

Save that as a userscript in Tampermonkey, and open a few tabs to http://example.com and check the console.

**Comment by ghost** [comment]
Thanks.I learn a lot from it .

**Comment by erikvold** [comment]
I'm going to archive the repo soon.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
