### ISSUE TITLE
does not work with recent versions of Firefox and Seamonkey

### ISSUE THREAD

**Issue by Flexmaen** [scriptish/scriptish#279]
Scriptish does not work anymore with Seamonkey 2.44+, or Firefox 44+.

_Error: Nicht definierte Entität
Source File: chrome://scriptish/content/closewindow.xul
Zeile: 13, Spalte: 5

Source: <key command="cmd_close" key="&closeCmd.key;" modifiers="accel"/>

Fehler: TypeError: 'addEventListener' called on an object that does not implement interface EventTarget.
Quelldatei: resource://scriptish/utils/Scriptish_localizeDOM.js
Zeile: 11

Fehler: 1472842085528   addons.manager  ERROR   Exception calling provider <unnamed-provider>.getAddonByID: ReferenceError: Scriptish_config is not defined (resource://scriptish/addonprovider.js:123:5) JS Stack trace: .getAddonByID@addonprovider.js [...]_

**Comment by marsjaninzmarsa** [comment]
+1, switched to Greasemonkey... 😢

Sadly, because Scryptish had nicer interface and cool scripts updating options...

**Comment by Atavic** [comment]
http://userscripts.org looks down.

**Comment by georgedorn** [comment]
http://userscripts.org/ has been down for _years_ and this project is evidently discontinued.
http://greasyfork.org/ is the most popular replacement script repository, but it's not clear if scriptish has a replacement.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
