### ISSUE TITLE
How could GM_xmlhttpRequest fetch the 'Location' in the Response Headers?

### ISSUE THREAD

**Issue by pendave** [scriptish/scriptish#280]
How could GM_xmlhttpRequest fetch the 'Location' in the Response Headers?

It displays status:200 when I use GM_xmlhttpRequest, but actually it needs to be 302.

![vrlq zv jqwuskkhgym 1ji](https://cloud.githubusercontent.com/assets/1331881/20571818/f2392d74-b1e3-11e6-9d9a-674e61011df9.png)

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
