### ISSUE TITLE
Setting routes on server object should not override  previous routes

### ISSUE THREAD

**Issue by clintonyeb** [scriptish/scriptish#285]
When you have two plugins each receiving an instance of the server object.

When plugin1 sets: server.routes([ {route1}, {route2'])
and plugin2 also sets more routes: server.routes([ {route1}, {route2'])

The route definition of the second plugin overrides the first plugin's routes definition and any request to the fist plugins endpoints return 404.

I wish routes definition to be added to already existing routes definitions if present and not override them.

Thank you. (Feature Request)

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
