### ISSUE TITLE
Feature Request: Replacing C++ auto and C# var as refactoring

### ISSUE THREAD

**Issue by Anysharp** [scriptish/scriptish#286]
Feature request for Visual Studio itself: Refactor by resolving and replacing "auto" (C++) or "var" (C#) at specific places in the code (if/where possible), so certainly not everywhere at once. It would also be handy if Intellisense could just only show how they would be resolved in the (by hovering over auto/var) tooltip.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
