### ISSUE TITLE
console.log.apply is not a function

### ISSUE THREAD

**Issue by aeosynth** [scriptish/scriptish#3]
first off, what happened to all the issues? I reported this earlier, but now that issue's gone, like it never existed.

Mozilla/5.0 (X11; Linux x86_64; rv:8.0a2) Gecko/20110828 Firefox/8.0a2

Scriptish0.1.4

``` javascript
function log() {
  console.log.apply(console, arguments);
}
log('test'); // TypeError: console.log.apply is not a function
```

**Comment by supahgreg** [comment]
All previously-created issues have been [saved](/scriptish/scriptish-issues-export)... I believe @erikvold is in the process of moving them to a better issue tracking system.

**Comment by aeosynth** [comment]
oh. well this was issue #499.

**Comment by erikvold** [comment]
http://scriptish.lighthouseapp.com/projects/83146/tickets/499-consolelogapply-is-not-a-function
