### ISSUE TITLE
Feature Request: GM_privateBrowsing to detect Private Browsing mode

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#44]
https://scriptish.lighthouseapp.com/projects/83146/tickets/584-feature-request-gm_privatebrowsing-to-detect-private-browsing-mode

**Comment by supahgreg** [comment]
What are your thoughts on `GM_info`?  Greasemonkey and Tampermonkey both provide that object, and not `GM_getMetadata`.  That might be a good place to keep this type of general script+environment info.

**Comment by erikvold** [comment]
> What are your thoughts on GM_info? ... That might be a good place to keep this type of general script+environment info.

Ya that sounds good to me @supahgreg so this now depends on #126

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
