### ISSUE TITLE
Scripts won't run script if clicked link opens in a new tab and stays on the same domain 

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#50]
https://scriptish.lighthouseapp.com/projects/83146/tickets/171-scripts-wont-run-script-if-clicked-link-opens-in-a-new-tab-and-stays-on-the-same-domain

**Comment by erikvold** [comment]
https://scriptish.lighthouseapp.com/projects/83146/tickets/602-target_blank-break-some-of-run-at-document-start-function

**Comment by erikvold** [comment]
https://scriptish.lighthouseapp.com/projects/83146/tickets/486-scripts-not-running-when-page-open-in-new-tab

**Comment by dindog** [comment]
I moved it here yesterday:
https://github.com/scriptish/scriptish/issues/18

You might want to mark one of them as duplication

**Comment by erikvold** [comment]
dup of #18
