### ISSUE TITLE
Add setting that would auto save homepageURLs if one is not defined. 

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#53]
https://scriptish.lighthouseapp.com/projects/83146/tickets/78-add-setting-that-would-auto-save-homepageurls-if-one-is-not-defined

**Comment by erikvold** [comment]
I'm leaning against this actually, I'm going to punt it, any one want to speak for it?

**Comment by supahgreg** [comment]
I think there would be an upside using the script's USO page if applicable and one wasn't explicitly set.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
