### ISSUE TITLE
HTMLElement.prototype is undefined

### ISSUE THREAD

**Issue by dindog** [scriptish/scriptish#57]
Hack like this is unavailable because one can't add method to HTMLDocument HTMLElement

https://github.com/csuwldcat/SelectorListener/blob/master/selector-listeners.js

testcase:

``` javascript
// ==UserScript==
// @name        test
// @namespace   test@dindog
// @include     http*
// ==/UserScript==
HTMLElement.prototype.test = function(){alert('Hello')};
document.body.test(); // Hello
```

The above script will prompt alert in content script , but not when running in wrapper, it will throw error " HTMLElement.prototype is undefined"

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
