### ISSUE TITLE
when i install a script,the drectory name doesn't contain the @name in chinese simplified

### ISSUE THREAD

**Issue by firefoxba** [scriptish/scriptish#59]
it a bug ,when a script was installed, the drectory name = @name+@namespace;  but  if   the @name contains chinese simplified(zh_cn), the drector name=@namespace ,if  two script have the same namespace ,and theri @name are all chinese  simplified  the two scripts'  drectory names are in conflict  under the same parent directory ;   one script will be replaced by the other script;
my English is so so  ,I  hope you can understand it . hope it  be resolved soon .  thanks  for  you extention

**Comment by dindog** [comment]
This's a valid bug. If you are the script author, you can simply add @id metadata to solve this problem.

**Comment by firefoxba** [comment]
I use GM  to write script ,an it doesnot contain the meta @id .and I donnot have the habit to write the meta @id  , some user  use scriptish to install the  script ,and the problen happended ; I think it is better to use the @name as the drectory name , or  scriptish can support ZH_cn  as the drectory name.

**Comment by supahgreg** [comment]
Is the userscript available for download somewhere?

**Comment by dindog** [comment]
it's easy to reproduce:
script A

``` javascript
 // ==UserScript==
// @name 脚本一
// @namespace  myname
// @include http*
// ==/UserScript==
alert('A');
```

script B

``` javascript
 // ==UserScript==
// @name 脚本二
// @namespace  myname
// @include http*
// ==/UserScript==
alert('B');
```

Same namespace, different name, and both name contains **no** ASCII characters, so the name after Scriptish trim is both empty string, as the result, the install directory will be the same too, namely @myname, installing one will override the other.

and @firefoxba: just add @id for you scripts' user best interests, it hurt nobody to add a line.

**edit**:spelling.

**Comment by firefoxba** [comment]
well, it is not that troublesome to add @id in my script  ,but the scriptish.org  have many scripts without  @id  and  have no ASCII char in @name  .It is a problem we cannot ignore.  By  the way ,are you Chinese  . your ID  looks like a Chinese

**Comment by erikvold** [comment]
Hmm well confirmed..
