### ISSUE TITLE
new features about GM_notification

### ISSUE THREAD

**Issue by jhdxr** [scriptish/scriptish#60]
I'm trying to use GM_notification to implement the webkitNotification, but I found I need some new features about GM_notification first.
GM_notification only supports text and onclick, so here are my suggestions:
1.msg supports html, or some tags, such as font, b, i, u, a
2.show() method supoorts to set the time how long the notification display
3.close() method. close the notification manually.

thx.

**Comment by supahgreg** [comment]
There are [limitations](https://developer.mozilla.org/docs/XPCOM_Interface_Reference/nsIAlertsService) to the code (currently) relied upon for `GM_notification`, so I'm not certain how many of those would be doable.

**Comment by jhdxr** [comment]
I checked that page. it seems that most of my suggestions (no. 2 and 3) are not able to be implemented. however, i found that the "alertfinished" method could be used to implement the "onclose" method in my script. could you add it in the next version?

GM_notification(msg, title, icon, callback_click, callback_close)

**Comment by erikvold** [comment]
> GM_notification(msg, title, icon, callback_click, callback_close)

I'm not sure what the use case for this would be.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
