### ISSUE TITLE
firefox mobile 16+ support

### ISSUE THREAD

**Issue by nevion** [scriptish/scriptish#63]
Did I miss something or is scriptish not supporting firefox mobile anymore since it dropped XUL? I'd absolutely love it if it worked on the android ff mobile.

If it's not currently working what needs to be sorted out?  Is it still feasible scriptish will work on ff mobile sometime in the near future?  Is there anyway I could help?  I have limited time but I am a C++ developer and I've cobbled together plunty of javascript as well using the FUEL apis.

**Comment by nodiscc** [comment]
confirming this on firefox mobile 20.0. Installing the addon fails with a "not compatible " error.

**Comment by ruharen** [comment]
I also would like Scriptish to be compatible with Firefox Mobile

**Comment by erikvold** [comment]
Scriptish has not supported mobile for a while, since the change to a Native UI and the droppping of E10s.  Unless a contributor gets to it, I have little time for a few months.

**Comment by fmcgorenc** [comment]
Aproximately how long till support for mobile is back on?

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
