### ISSUE TITLE
access to modify referrer

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [scriptish/scriptish#65]
Hello, I have a small question. Is there any possibility for implement
to Scriptish changing document.referrer frome JS code before we send
forms or change URLs?

It will be very nice, because now we can't send form frome different
page - even if we are in the same domain (if server-side developer
check this parameter).

Of course this option must be available in JS code (want using
dynamically - run depending on actuall localization) sth like this:

GM_setReferrer("my_site_adres");
form.submit(); // send my changing referrer

I know block changing refferer is because security restriction, but if
you put this posibility run on in Scriptish option (everyone must do
it manual) problem will be less. Eventualy change refferer will be
possible only for actual domain - we can only change part URL after
hostname << this is sufficient.

In Firefox we have extension for this action
https://addons.mozilla.org/en-US/firefo ... efcontrol/ but it is
insufficient when working with scripts - but idea is great:) I will
ask developer Tampermonkey if it possible implement on Google Chrome.

**Comment by erikvold** [comment]
Well it's easy to modify the referrer header for connections, mapping a connection to a userscript is the tricky part..

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
