### ISSUE TITLE
Auto-update initially turned off

### ISSUE THREAD

**Issue by CoolCmd** [scriptish/scriptish#67]
After new script being installed, its auto-update is turned off even if valid @updateURL and @downloadURL provided. In this situation auto-update must be DEFAULT like for Firefox add-ons and scripts when Greasemonkey installed.

**Comment by CoolCmd** [comment]
How many people use a command "reset all addons to update automatically"? 1% or even whole 2%?
The switched-off auto-updating is anachronism.

**Comment by erikvold** [comment]
This worksforme already.
