### ISSUE TITLE
I can't install or update scripts using GM_config

### ISSUE THREAD

**Issue by Exomancer** [scriptish/scriptish#68]
I get the following error:

Error loading dependency: http://github.com/sizzlemctwizzle/GM_config/raw/master/gm_config.js
Error! Server returned: nothing (timed out)

I searched the problem online and it seems that it may be an issue with Scriptish.

"Looks like the github url is redirecting to a https url and Scriptish seems unable to handle this redirection."

Please see the following for the complete thread:

http://userscripts.org/topics/97248

I installed GM_config manually so the dependency was met but the error remains.

This is affecting me updating  a script that I use extensively that is now broken.  If unfixed I will need to return to using GM instead of Scriptish.

Thanks.

**Comment by erikvold** [comment]
> "Looks like the github url is redirecting to a https url and Scriptish seems unable to handle this redirection."

That's a security feature, change the url to be `https` and it will be fine, Scriptish wouldn't be allowed on AMO if it allowed the above redirection.

> I installed GM_config manually so the dependency was met but the error remains.

I don't know what you mean here, can you explain?

You can disable the 'secure' requirement after installing Scriptish in the preferences window > Advanced > Update Security, then deselect 'require userscripts to use https to update'.  I recommend re-selecting this after you have completed your updates tho, and trying to convince the developers of the scripts that are not updating securely to use https when possible.
