### ISSUE TITLE
GM_apiLeakCheck issue when stack.filename is "self-hosted"

### ISSUE THREAD

**Issue by supahgreg** [scriptish/scriptish#69]
When calling an API function from within a [self-hosted JS builtin](https://developer.mozilla.org/docs/SpiderMonkey/Internals/self-hosting) (e.g. `Array#forEach`), at a certain point the `stack.filename` will be "self-hosted" (when `stack.name` === "forEach").  This value causes `GM_apiLeakCheck` to throw an access violation error, since it doesn't begin with "chrome".

``` javascript
// ==UserScript==
// @id             bug462300test@phob.net
// @name           Mozilla bug 462300 test
// @include        http://phob.net/*
// @run-at         document-end
// ==/UserScript==

// Does not work.
["bar"].forEach(function(aThing) {
  GM_setValue("foo", aThing);
});
```

Currently @ `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:20.0) Gecko/20121201 Firefox/20.0`

Info:
https://bugzilla.mozilla.org/show_bug.cgi?id=462300
http://hg.mozilla.org/mozilla-central/annotate/ecdf0e332f17/js/src/jscntxt.cpp#l383
https://developer.mozilla.org/docs/SpiderMonkey/Internals/self-hosting

**Comment by nmaier** [comment]
Fixed upstream, isn't it?
https://bugzilla.mozilla.org/show_bug.cgi?id=844406
https://bugzilla.mozilla.org/show_bug.cgi?id=853417

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
