### ISSUE TITLE
Script cannot install, dependency error.

### ISSUE THREAD

**Issue by Zegnat** [scriptish/scriptish#71]
I tried to install the [Backbars](https://github.com/elzr/Backbars/) script via GitHub: [backbars.user.js](https://raw.github.com/elzr/Backbars/master/backbars.user.js). However, I get the following error:

> Error loading dependency: http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js
> Error! Server returned: nothing (timed out)

However, it seems like I can access the jQuery file both through my browser as well as through the Mac Terminal by use of cURL. Might be a bug with Scriptish & `@require`.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
