### ISSUE TITLE
Userscript cannot be installed if @require or @resource is using URL redirection

### ISSUE THREAD

**Issue by LouCypher** [scriptish/scriptish#72]
For example:

```
// @require https://github.com/username/reponame/raw/master/filename.js
```

or

```
// @resource resourcename https://github.com/username/reponame/raw/master/filename.txt
```

Error message:

> Error loading dependency: https&#x003A;//github.com/username/reponame/raw/master/filename.ext
> Error! Server returned: 302: Found

It works only if it's using direct URL.

```
// @require https://raw.github.com/username/reponame/master/filename.js
```

or

```
// @resource resourcename https://raw.github.com/username/reponame/master/filename.txt
```

Greasemonkey has no problem if the userscript is using URL redirection or not.

**Comment by ghost** [comment]
Same problem here. I can't install this script: http://userscripts.org/scripts/show/24464
Not the first time it happen to me :-/

**Comment by LouCypher** [comment]
Test case: install [this userscript](https://raw.github.com/LouCypher/userscripts/master/scriptish/userscript.user.js).

**Comment by LouCypher** [comment]
With [Version 0.1.9](https://addons.mozilla.org/addon/scriptish/versions/0.1.9), it's getting worse. Script still can't be installed and 
Scriptish can't display error in console

```
Error: console is not defined
Source file: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js
Line: 34
```
