### ISSUE TITLE
Multi-line CSS fails in GM_addStyle

### ISSUE THREAD

**Issue by salagadoola** [scriptish/scriptish#74]
https://github.com/scriptish/scriptish/wiki/GM_addStyle
GM_addStyle((<><![CDATA[
  body { color: white; background-color: black }
  img { border: 0 }
  .footer {width:875px;}
]]></>).toString());

The above example no longer works.
It generates "SyntaxError: syntax error" in F12 debug console.

**Comment by LouCypher** [comment]
Not Scriptish issue.

E4X is obsolete
https://developer.mozilla.org/en-US/docs/E4X

For workaround, see
http://wiki.greasespot.net/Multi_Line_Strings

**Comment by nmaier** [comment]
@LouCypher is correct

**Comment by salagadoola** [comment]
Thanks.
Just edited the wiki page and removed the cdata example.
