### ISSUE TITLE
GM_safeHTMLParser may strip href tags

### ISSUE THREAD

**Issue by claudenobs** [scriptish/scriptish#76]
GM_safeHTMLParser may strip href tags from anchor elements. I experienced this by parsing audible.com html pages loaded via xmlhttprequest. i suspect this is due to malformed html. console logs errors about malformed meta tags... guess it's not xhtml...

the following works though:
let doc = document.implementation.createHTMLDocument("");
doc.documentElement.innerHTML = this.responseText;

**Comment by erikvold** [comment]
can you provide a simple example snippet that reproduces this behavior please?

**Comment by claudenobs** [comment]
I know this is not really a testcase, as it relies on an external website that may change at any time, but it is what it is. the output should be the same, but it is not.....
Userscript:

```
let r = new XMLHttpRequest();
r.open("GET", "http://www.audible.com", true);
r.onload = function(e) { console.log(GM_safeHTMLParser(e.target.responseText).querySelector('.adbl-prod-title a').href); };
r.send(null);
r = new XMLHttpRequest();
r.open("GET", "http://www.audible.com", true);
r.responseType = 'document'; // html
r.onload = function(e) { console.log(e.target.response.querySelector('.adbl-prod-title a').href); };
r.send(null);
```

Output:

```
[00:01:51.947] [test@blunet.cc] 
[00:01:54.094] [test@blunet.cc] http://www.audible.com/pd/ref=hp_1?asin=B00995OCUG
```

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
