### ISSUE TITLE
@document-start : window.location.reload(true) loads previous page

### ISSUE THREAD

**Issue by CoolCmd** [scriptish/scriptish#77]
``` javascript
// ==UserScript==
// @id             reload-fail
// @run-at         document-start
// @include        https://github.com/scriptish/scriptish/issues/*
// @noframes
// ==/UserScript==

console.log(window.location.href);
window.location.reload(true);
```
1. Go to https://github.com/scriptish/scriptish/issues
2. Click on any issue, for example https://github.com/scriptish/scriptish/issues/67

Expected result: endless reload https://github.com/scriptish/scriptish/issues/67
Actual result: firefox loads https://github.com/scriptish/scriptish/issues

Erik, please fix https://github.com/scriptish/scriptish/issues/16. After that scriptish becomes compatible with greasemonkey and, i think, window.location.reload() will be fixed.

**Comment by erikvold** [comment]
This works now.
