### ISSUE TITLE
Userscripts.org ratings aren't being properly retrieved

### ISSUE THREAD

**Issue by ScottSteiner** [scriptish/scriptish#78]
For example, [this script](https://userscripts.org/scripts/show/77506) has 5 reviews and an average rating of 4.8 in its [meta.js](https://userscripts.org/scripts/source/77506.meta.js), but Scriptish returns "undefined reviews" rather than the proper rating.

The same thing happens with [this dummy script](https://userscripts.org/scripts/show/157933), which has 0 reviews and also returns "undefined revuews" as its rating

**Comment by supahgreg** [comment]
Not to say it shouldn't be handled better, but I didn't have a problem with either userscript mentioned until USO was having issues (500 errors, etc.) earlier this week.
