### ISSUE TITLE
Implement @block

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#81]
@block should use a match pattern to determine what resources to block when the @include/@match matches the request url.

This way a user script can block a image, and replace with another, or block a script and replace that.

**Comment by SlimShayD** [comment]
How about @block-match-domain and @block-match-url? Matching domain-only would help writing and matching patterns to block certain third-party requests.

**Comment by KOLANICH** [comment]
Don't think it is a good idea to transform Scriptish into AdblockPlus. Maybe better to make it possible to add AdblockPlus rules on script installation?

**Comment by erikvold** [comment]
I want this.  I'd like to be able to write a script that blocks & replaces ads on a page with something useful, and I don't think that we should require/rely on another add-on like adblock to do this.

**Comment by erikvold** [comment]
Oh ya @block doesn't have to be limited to ads only... it could be used to overload poorly written javascript provided by say Facebook to pick an easy target.  Or it could overload tracking software like google analytics.  Much more too I'm sure.

**Comment by erikvold** [comment]
Some more evidence this is needed:
- http://stackoverflow.com/questions/13106250/using-greasemonkey-to-prevent-downloading-of-a-script
- http://stackoverflow.com/questions/3972038/stop-execution-of-javascript-function-client-side-or-tweak-it

It appears there are people using `document-start` and trying to block elements that use resources before they are attached/used to/by the document.

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
