### ISSUE TITLE
add coffeescript support

### ISSUE THREAD

**Issue by flying-sheep** [scriptish/scriptish#82]
coffeescript is a terser way to write javascript and compiles to javascript in a foreseeable way. thus it is perfect for userscripts: one would simply fire up the user script editor, tick the “coffeescript” checkbox and hack away, allowing for faster writing of quick scripts.

there are [hacks](https://gist.github.com/saihoooooooo/3447066) to allow it, but e.g.  `myscript.user.coffee` would gain syntax highlighting unlike a solution that involves compiling and evaluating a multiline string, and, also unlike the latter, it wouldn’t need boilerplate.

finally, scripts distributed as coffeescript (unlike the compiled javascript) are better to read and learn from, and don’t need extra effort in terms of linking the coffee script source and using build tools.

**Comment by erikvold** [comment]
+1 and use [SourceMap.jsm](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/SourceMap.jsm)

**Comment by erikvold** [comment]
Actually I'm going to -1 this because I don't want to enter a rabbit hole where we start supporting `user.java` and `user.python` etc all compiled to js..  part of the reason why I developed Scriptish was because it is a tool to teach people JavaScript.

**Comment by erikvold** [comment]
I think this is a good idea for a new add-on tho, CoffeeScriptish!

**Comment by flying-sheep** [comment]
Hmm, I think your concern that all kinds of people will request all kinds of JS preprocessors is valid.

Nevertheless I filled this feature request, because
1. CoffeeScript is easily the most used one (look at Github’s language statistics) and
2. Because it supports features like ECMA 6’s today. In fact ECMA 6 is partly inspired by CoffeeScript

So I think supporting it while saying “not gonna implement more preprocessors unless there is a huge shift in user bases” is reasonable.
