### ISSUE TITLE
Warn when scripts take particularly long to execute.

### ISSUE THREAD

**Issue by nmaier** [scriptish/scriptish#83]
What "particularly long" means is to be figured out. I guess it would be easy to look at what mozilla and/or gecko profiler considers "long".

At least look at the execution time of the initial eval-in-sandbox.
Other prime targets are:
- any GM API callbacks, such as XHR
- setTimeout/setInterval
- requestAnimationFrame (mozRequestAnimationFrame)
- event listeners (although observing when a user scripts adds these and then proxy them can be quite tricky I imagine)

**Comment by erikvold** [comment]
I'm going to archive the repo soon.
