### ISSUE TITLE
GM_addStyle() with @run-at document-start fails silently

### ISSUE THREAD

**Issue by ayanamist** [scriptish/scriptish#90]
It's a bug introduced from GreaseMonkey.
https://groups.google.com/forum/?fromgroups=#!topic/greasemonkey-users/rx2xc6HI2us
As i remember, scriptish does not support firefox 3.6, so can you make some changes?

**Comment by erikvold** [comment]
Jetpack implemented a new style sheet agent for PageMod contentStyles which we should be using for GM_addStyle imo, with this we could also provide an `@css` or `@stylesheet` feature.

**Comment by erikvold** [comment]
This might work now b/c of 2e5fe19ed7ee6bc4c592c89429fbe57017e1da89. Tomorrow there will be a new nightly built using the change so can someone please try this and confirm if this is an issue still or not for me please?

**Comment by erikvold** [comment]
ok I confirmed this bug was a bug, and it is now fixed in the nightly.
