### ISSUE TITLE
Use unsafeWindow in setTimeout callback throw an error

### ISSUE THREAD

**Issue by yume-chan** [scriptish/scriptish#91]
Just use the following code

``` javascript
setTimeout(function() { unsafeWindow.document }, 200);
```

Then Firefox show this error
`Illegal operation on WrappedNative prototype object`
My friend told me that codes like this works on GreaseMonkey.

Firefox nightly 23.0a1 + Scriptish 0.1.8

**Comment by kmod-midori** [comment]
This code works on Tampermonkey with Google Chrome 26.0.1410.43 m.

**Comment by ghost** [comment]
Try `window.setTimeout` instead of just `setTimeout`. I opened a bug report for this here: https://github.com/scriptish/scriptish/issues/89

**Comment by yume-chan** [comment]
@kuehlschrank Yes it should be same bug.

**Comment by erikvold** [comment]
duplicate of #89
