### ISSUE TITLE
[Nightly]Edit and Open Folder buttons are missing in nightly

### ISSUE THREAD

**Issue by yume-chan** [scriptish/scriptish#92]
Not sure from which build.
Screenshot:
![Capture](https://f.cloud.github.com/assets/1330321/433224/e3ca86fc-aec2-11e2-9070-451b0d09c25b.PNG)
Stable 20.0.1 doesn't have this problem.
Screenshot of same profile in stable:
![Capture](https://f.cloud.github.com/assets/1330321/433232/7d3bbee6-aec3-11e2-8f9e-76f59acb7ec4.PNG)

**Comment by jonnzzo** [comment]
The same is happening now with the current version of Aurora (23.0a2):  No **edit** or **open folder** buttons are visible in Addon Manager.
