### ISSUE TITLE
Add private argument to GM_xhr

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#93]

**Comment by nmaier** [comment]
`makePrivate` is now documented

**Comment by nmaier** [comment]
@erikvold This kinda also fixes #94 I think, or what is missing.

**Comment by erikvold** [comment]
> @erikvold This kinda also fixes #94 I think, or what is missing.

@nmaier Cool! I just want to ignore the download url record keeping when the install window is private, we could just disable it altogether for the time being too..
