### ISSUE TITLE
Can not download the updated scirpts.

### ISSUE THREAD

**Issue by efreeking** [scriptish/scriptish#95]
Browser Version: firefox 20.0.1
Scriptish Version: 0.1.8
When I check the update of the scripts, then notify there are some updates for the scripts.
But when I click the update button, it says "Error downloading xxxxxx", and the update can not download and install.
Script example: Userscripts.org Scam Filter

**Comment by erikvold** [comment]
Is this still an issue?

**Comment by erikvold** [comment]
Script updates require https for updates by default, you can change this in Scriptish preferences (but I would not recommend that..).  I'm just guessing that is the issue, but it seems to pop up a quite a bit.

Closing this issue for now, tell me if I am wrong and we can reopen it.
