### ISSUE TITLE
Scriptish doesn't load resources correctly if the server uses SPDY

### ISSUE THREAD

**Issue by KOLANICH** [scriptish/scriptish#96]
Scriptish doesn't load resources correctly if the server uses SPDY.

**Comment by nmaier** [comment]
Please elaborate and include some steps to reproduce

**Comment by KOLANICH** [comment]
try to install this http://userscripts.org/scripts/show/132113

**Comment by nmaier** [comment]
works for me...

**Comment by nmaier** [comment]
Also, there isn't really any spdy involved?

**Comment by KOLANICH** [comment]
Are you sure?
https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js , look to firebug's network tab.

**Comment by KOLANICH** [comment]
Also it doesn't work, if i try to install it says it is unable download dependency.
Under both OSes (XP and 8).
