### ISSUE TITLE
setTimeout breaks after Firefox 22 and later

### ISSUE THREAD

**Issue by 0rt** [scriptish/scriptish#98]
```
// ==UserScript==
// @name          test alert
// @version        0.0.1
// @namespace      testalert@ort.com
// @include        http*
// @run-at         document-end
// ==/UserScript==
setTimeout('alert("test")',300);
```

throw error :
[09:06:51.226] NS_ERROR_XPC_BAD_OP_ON_WN_PROTO: Illegal operation on WrappedNative prototype object @ chrome://scriptish/content/scriptish.js -> 

Firefox 21 and earlier version work fine.

**Comment by yume-chan** [comment]
Same as Issue #89
